### DISCUSSION TITLE
Sling support of array data type

### DISCUSSION THREAD

**Discussion by matanper** [slingdata-io/sling-cli#178] [Q&A] [answered]
I try to copy between 2 postgres databases a table with array of uuid, and I get warning `WRN using string since type '_uuid' not mapped for col 'foo': ""`
It still copies the data as varchar column, however if the array is too large I get `pq: value too long for type character varying(255)`

code to reproduce:
```sql
create table test_table  (
	"id" uuid,
	"foo" _uuid
);

INSERT INTO test_table (id, foo) VALUES (gen_random_uuid(), ARRAY[gen_random_uuid(), gen_random_uuid()]);
```

```yaml
source: LOCAL_PG
target: LOCAL_PG

defaults:
  mode: full-refresh 
  object: 'test.{stream_table}'

streams:
  public.test_table:
```

**Comment by flarco** [comment]
Thanks, Fixed in https://github.com/slingdata-io/sling-cli/issues/179

**Reply by matanper** [reply]
Thanks 🙏 
so it isn't possible to sync between 2 databases of the same type and keep the original type of all the columns?

**Reply by flarco** [reply, marked as answer]
Ah I see. Sling uses JSON for any semi-structure/nested data. At the moment, it doesn't support native arrays (each database has it's own syntax for arrays). What I'm thinking is to have sling auto-convert the native array form source when selecting and writing into target as json (see #179). But writing into a native array on target is a bigger lift. The work-around is, on target side, you could use a `target.options.post_sql`, to convert the json values into native array.

**Reply by matanper** [reply]
Thanks, got it working with:
```
streams:
  public.test_table:
    source_options:
      columns:
        foo: text
    target_options:
      post_sql:
        "alter table test.test_table alter column foo type _uuid using foo::_uuid"
```
