### DISCUSSION TITLE
Allow environment variables in source sql

### DISCUSSION THREAD

**Discussion by matanper** [slingdata-io/sling-cli#189] [Ideas]
Hey, It would be great if it will be possible to do something such as: 
```yaml
source: LOCAL_PG
target: LOCAL_PG

defaults:
  mode: full-refresh 
  object: 'test.{stream_table}'

streams:
  public.test_table:  
    sql: |
      select * from public.test_table where created_at > (current_date - interval '{num_days} days')

env:
  num_days: '${num_days}'
```

EDIT:
looking [here](https://github.com/slingdata-io/sling-cli/blob/b5c89569b93b06fa557bffb6990b5f9967eb7fb9/core/sling/task_run_read.go#L203) it seems it should work, but I'm getting `error="pq: syntax error at or near \"{\""`
