### DISCUSSION TITLE
Is there a way to replicate all tables in a database to target?

### DISCUSSION THREAD

**Discussion by alberttwong** [slingdata-io/sling-cli#219] [Q&A] [answered]
something like

```
atwong@Albert-CelerData ~ % sling run --src-conn DUCKDB  --src-stream 'duckdb.main.*' --tgt-conn STARROCKSLOCAL --tgt-object 'testing.*' --mode full-refresh
```

**Comment by flarco** [comment, marked as answer]
Yes, but you need a replication.yaml file, see https://docs.slingdata.io/sling-cli/run/configuration/replication#overview:

```
source: MY_POSTGRES
target: MY_SNOWFLAKE

# default config options which apply to all streams
defaults:
  mode: full-refresh
  object: new_schema.{stream_schema}_{stream_table}

streams:
  my_schema.*:

```
