### DISCUSSION TITLE
How to make the stream schema dynamic?

### DISCUSSION THREAD

**Discussion by somiandras** [slingdata-io/sling-cli#238] [Q&A] [answered]
I'm building replication from MySQL transactional db to Postgres, and it turned out that the db I can use for dev/testing purposes is named differently from the final (eg. `mydb_staging` and `mydb_prod`), ie. if I write stream keys like `mydb_staging.my_table` in `replication.yaml`, it won't work on prod (or the other way around, if I use `mydb_prod`, I can't run it in dev). I don't have control over the db names and how I can access them.

Is there a way to define the schema somewhere and use interpolation in the stream keys? Something like 

```yaml
streams:
  {schema_from_envvar}.my_table:
    ...
```

**Comment by flarco** [comment, marked as answer]
Just checked over the logic, the stream name doesn't get formatted, so it won't work. I'll enable that next release.

As a workaround, try this (the custom SQL does get formatted):

```yaml
defaults:
  sql: "select * from {schema}.{stream_name}"

streams:
  my_table:

env:
  schema: '${SCHEMA}'   # From Environment
```

**Reply by somiandras** [reply]
Thanks, this is awesome.

**Reply by somiandras** [reply]
**Update**: this doesn't seem to work if I add `sql` to the `defaults`, only if I define `sql` on each of the streams, where necessary (the variable is interpolated nicely).

**Reply by flarco** [reply]
Interesting, that was a bug fixed by #211. Are you using the latest version?

**Reply by somiandras** [reply]
I'm on 1.2.1.

**Reply by somiandras** [reply]
Wait, I'm in a weird place actually...  I'm installing Sling via dagster-embedded-elt in a Docker container.

<img width="234" alt="image" src="https://github.com/slingdata-io/sling-cli/assets/12885402/e458b7fe-0f56-4741-a636-0c709e620513">

**Reply by flarco** [reply]
Could you share your config? I ran this and it worked fine:

```yaml
source: postgres
target: sqlite

defaults:
  mode: full-refresh
  object: 'main.pg_{stream_table}'
  sql: "select *, 'hi' there from {stream_name}"

streams:
  public.my_table*:
```

It rendered to `select *, 'hi' there from "public"."my_table2"`
