### DISCUSSION TITLE
Example for table_ddl option usage?

### DISCUSSION THREAD

**Discussion by mzapukhlyak** [slingdata-io/sling-cli#33] [Q&A] [answered]
Could you give an example of the table_ddl option? I haven't found the case in the documentation yet.

I have one highly deep and very large json file in multiple chunks, and it appears that sling is able to import the single chunk correctly, building a nice table in the PostgreSQL DB. Some field types still need to be specified more precisely/differently, so I decided to do it for the entire table using DDL file.

Can ddl be provided as a sql file, or which format of the table_ddl is expected here?

**Comment by flarco** [comment]
Sure, however, let me first ask, have you tried to ingest the whole folder of JSON files instead of just one by one? Sling should be able to iterate over all of them and attempt to add columns as they are discovered (assuming you are flattening with source option `flatten: true`). For the types, it's a tricky thing, so there is the target option `adjust_column_type`, which defaults to `false`. Sling will attempt to adjust the column type as values are discovered. Can you try turning it on? 

Feel free to share your config and/or JSON structure sample.

<img width="776" alt="image" src="https://github.com/slingdata-io/sling-cli/assets/7671010/bddae833-a366-4434-8706-7204615f9005">

**Comment by flarco** [comment, marked as answer]
For the `table_ddl`, here is a [replication](https://docs.slingdata.io/sling-cli/replication) YAML example.

```yaml
source: S3
target: PG

streams:
  's3://bucket/path/to/json_folder':
    source_options:
      flatten: true
    target_options:
      table_ddl: |
         create or replace table "my_schema"."my_table" ( 
         .... 
         )
    object: '"my_schema"."my_table"' # make sure to fully qualify so matches in DDL
    mode: full-refresh
```
