### DISCUSSION TITLE
Using wilcard in postgres

### DISCUSSION THREAD

**Discussion by datvt-vitox** [slingdata-io/sling-cli#339] [Q&A] [answered]
Currently I'm using this replica config to move all table from schema postgres_air in database postgres_air to schema air_pg in database postgres
```yaml
source: postgresql://admin:admin@172.31.211.223:5432/postgres_air?sslmode=disable
target: postgresql://admin:admin@172.31.211.223:5432/postgres?sslmode=disable

defaults:
  object: '{air_pg}.{postgres_air}_{stream_table}'
  mode: full-refresh

streams:
  postgres_air.*:
  ```

But the error appear
 ```
fatal:
--- proc.go:267 main ---
--- sling_cli.go:442 main ---
--- sling_cli.go:474 cliInit ---
--- cli.go:286 CliProcess ---
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--- sling_run.go:188 processRun ---

--------------------------- postgres_air.* ---------------------------
--- task_run.go:99 func1 ---
--- task_run.go:523 runDbToDb ---
--- task_run_read.go:61 ReadFromDB ---
~ execution failed
--- database.go:1430 GetSQLColumns ---
~ Could not ReadFromDB
--- database.go:1568 GetColumns ---
~ Could not get source columns
--- database.go:1491 GetTableColumns ---
did not find any columns for "postgres_air".*. Perhaps it does not exists, or user does not have read permission.
``` 

When I change stream to 
```yaml
streams:
  postgres_air.account:
    object: air_pg.account
```
It work perfectly. I don't know it's my mistake when using wilcard  notation or this is a bug.
