### DISCUSSION TITLE
What's the best way to implement Daily Snapshot using Sling?

### DISCUSSION THREAD

**Discussion by karhendana** [slingdata-io/sling-cli#346] [Q&A] [answered]
In Functional Data Engineering concept, daily snapshot is useful for providing a historical record for analysis and reporting.
In BigQuery, it's implemented using daily partition, enabling independent processing of data for each day.
Sling has snapshot mode with `_sling_loaded_at` column with int64 type.

How can Sling's snapshot mode be optimally utilized to create daily snapshots that align with BigQuery's daily partitioning for efficient historical data analysis and reporting?

**Comment by flarco** [comment]
Hey, while testing the following replication example below, I found lacking logic, which has been fixed [here](https://github.com/slingdata-io/sling-cli/pull/344/commits/df08b62d1650c5d792e9cff8b8e7a1071e1cd1e5).
Below should work well using this [branch](https://github.com/slingdata-io/sling-cli/pull/344):

```yaml
source: postgres
target: bigquery

streams:
  public.table:
    object: public.test_snapshot
    mode: snapshot
    target_options:
      table_keys:
        partition: [date(_sling_loaded_at)]

env:
  SLING_LOADED_AT_COLUMN: timestamp
```

**Comment by flarco** [comment, marked as answer]
You could also do this (should work with current version):

```yaml
source: postgres
target: bigquery

streams:
  public.table:
    sql: "select *, current_date as snapshot_date from {stream_name}"
    object: public.test_snapshot
    mode: snapshot
    target_options:
      table_keys:
        partition: [snapshot_date]
```
