### DISCUSSION TITLE
sling connection to clickhouse with SSL and server certificate

### DISCUSSION THREAD

**Discussion by igrpon** [slingdata-io/sling-cli#419] [Q&A] [answered]
How could I setup sling connection to clickhouse with SSL and server certificate.

Currently I have YAML config like this:

```
connections:
  DWH_CH:
    type: clickhouse
    host: host.net
    port: 8443
    database: prod-01
    user: root
    password: **********
    http_url: https://root@host.net:8443
```

But I got the following error:
```
fatal:
~ could not connect to database
clickhouse [dsn parse]: https without TLS
```
