### DISCUSSION TITLE
Partitioning of file based targets

### DISCUSSION THREAD

**Discussion by nixent** [slingdata-io/sling-cli#432] [Q&A] [answered]
I'd like to run a backfill from SQL server to parquet files stored in ADLS and partition target data by date parts of `update_key` column, like `raw/my_system/{stream_table}/YYYY({update_key})/MM({update_key})/DD({update_key})`

Currently timestamp variables YYYY, DD, MM are calculated based on run timestamp. Is there any way to make it to take `update_key` instead?

As a workaround I'm running multiple backfills and controlling partitions like this:
```YML
source: sql_source
target: adls_target

defaults: 
  mode: backfill
  object: raw/my_system/{stream_table}/{partition}/
  primary_key: my_key
  source_options:
    range: '{start_date},{end_date}'  
  target_options:
    format: parquet
      
streams: 
  dbo.MyTable:
    update_key: TransDate  

env:
  start_date: '${START_DATE}'
  end_date: '${END_DATE}'
  partition: '${PARTITION}'
```
