### DISCUSSION TITLE
Use bach size prop in database to database

### DISCUSSION THREAD

**Discussion by calebeaires** [slingdata-io/sling-cli#442] [Q&A] [answered]
Since sling uses bcp as a driver, can we make use of `-b` param to define the batch size of the target? If yes, how can I use it?

```bash
./sling run --src-conn MY_HOUSE --src-stream 'orders' --tgt-conn MY_SERVER --tgt-object 'Eclipse2024.orders' --mode full-refresh
```

**Comment by flarco** [comment, marked as answer]
Can you try the latest [dev build](https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds)? It will accept the new property `bcp_extra_args` in your `env.yaml`.

For example:

```yaml
  MSSQL:
    type: sqlserver
    database: master
    host: msserver
    port: 1433
    user: sa
    bcp_extra_args: ["-b", "5000"]
```
