### DISCUSSION TITLE
MSSQL -> Azure Blob using DuckDB

### DISCUSSION THREAD

**Discussion by EValge-IT** [slingdata-io/sling-cli#504] [Q&A] [answered]
I have recently upgraded slingCLI to the latest version but I've noticed some strange behaviour now when trying to transfer data over from an Azure MSSQL DB to an Azure Storage Account.

The previous version I used (1.3.2) worked a treat for my use case. I was able to specify `file_max_rows` and Sling would batch the database perfectly not pulling more than it needed to memory. This was the old replication.yaml I was using:

```
    source: MSSQL
    target: AZURE_STORAGE
    defaults:
      mode: full-refresh
      target_options:
        format: 'parquet'
        file_max_rows: 5000000
        transforms: [decode_utf8]
    streams:
      dbo.test:
        object: 'https://<STORAGE_ACCOUNT_NAME>.blob.core.windows.net/<CONTAINER_NAME>/{stream_table}'
        sql:
          SELECT *
          FROM dbo.test
``` 

However, now that Sling is using DuckDB I'm seeing that the replication task no longer supports `file_max_rows`. This isn't too much of an issue as using `file_max_bytes` is fine for my use case. 

However, what I've noticed is that the first step is for Sling to seemingly ingest the entire table to DuckDB before creating the files and pushing them to the storage account. As you can probably imagine this pretty quickly leads to a OOMKilled error.

For context, I ran SlingCLI against my dataset and within 5 minutes of running it was already using 12GB of memory. In terms of rows it had read it was less than 25% of the table I was working on. (In this case the table was only 89GB).

Is this the intended behaviour? If so how do users run Sling when working with large tables (in my case its 300GB) without being OOMKilled. Or is there a way to stop DuckDB having the entire table ingested and instead only take smaller batches for processing and deleting them from DuckDB before proceeding the the next batch?

I know I can set `SLING_DUCKDB_COMPUTE` to false to return to the previous behaviour. However, I fear that it won't be supported for too much longer or has inherent problems which is why DuckDB was introduced.
