### DISCUSSION TITLE
Rename or skip columns while loading

### DISCUSSION THREAD

**Discussion by igrpon** [slingdata-io/sling-cli#573] [Q&A]
Is it possible to **rename or skip** some columns while loading ?

e.g.

1. if in source CSV file or db table the column is named "price", but I would like to load into target's "amount" column ?
2. if there are some columns in source CSV file or db table that I just wan't to skip (or e.g. an empty column) ?

I was thinking about **target_optoins: columns** map, but it looks like this functionality is not available, I would say it is rather easy to implement, e.g. add subkeys:

```
column:
  source_column_name:
    skip: true | false
    datatype: "same as currently available"
    name: "target_name"
```
https://docs.slingdata.io/concepts/replication/columns

For now I need to preprocess file or do post-processing in the db, yes it is trivial, but this functionality would same much time.
Thks.
