### DISCUSSION TITLE
Database to file strange file size

### DISCUSSION THREAD

**Discussion by DennyLokoOnfly** [slingdata-io/sling-cli#580] [Q&A]
Hello,

I've had Swing configured to run for a few weeks now, but something strange has started happening. One database keeps growing regularly, as expected, and it seems that Sling is able to collect its data, as shown in the logs. However, the file size of the output file appears to have been reset.

What could have caused this?

It's worth mentioning that every execution has finished successfully. Not only does the file size seem incorrect, but the data in the file itself is also missing. I'm using the free version of Sling.

Thanks!

```yaml
source: BOOKING
target: S3_EXPORT

defaults:
  primary_key: id
  object: booking/{stream_schema}/{stream_table}/{YYYY}_{MM}_{DD}_{HH}_{mm}_{ss}.parquet

  target_options:
    format: parquet

streams:
  main_booking.*:

  main_booking.customers:
    columns:
      birthday: string

  main_booking.hotels:
    columns:
      check_in_hour: string
      check_out_hour: string
  
  main_booking.migrations:
    disabled: true

env:
  SLING_ALLOW_EMPTY: TRUE
```

Logs showing the increasing size of the table:
![Screenshot 2025-06-20 at 15 05 01](https://github.com/user-attachments/assets/04b20e50-896b-4872-90b8-518d5345aacb)

Output files:
![Screenshot 2025-06-20 at 15 04 34](https://github.com/user-attachments/assets/0b2592fe-c028-479d-831b-4c5c7033a12b)
