### DISCUSSION TITLE
Can variables defined in ~/sling/env.yaml file be referenced by other task / replication yaml files

### DISCUSSION THREAD

**Discussion by ShahBinoy** [slingdata-io/sling-cli#83] [General]
Hi @flarco,

The docs at https://docs.slingdata.io/sling-cli/run/configuration#object-patterns mentions that there are lot of inbuilt variables that can be used to add some dynamic patterns for naming objects, etc. 

Is it possible to use the variables defined in the `variables` section of `env.yaml` file be accessed by all other task/replication/cli definitions via the `{variable_name}` convention ?

my `env.yaml` file

```
connections:
  S3_LAKE_ZONE_A:
    type: s3

variables:
  path_prefix: /dev-binoy/elt/data_landing

```

my `replication.yaml` file

```
source: MY_MYSQL
target: S3_LAKE_ZONE_A

defaults:
  object: {path_prefix}/{stream_schema}/{stream_table}/{YYYY}_{MM}_{DD}.parquet < - Use Path Prefix ?
  target_options:
    format: parquet

streams:

  # all tables in schema, except "forbidden_table"
  my_schema.*:
    object: {stream_schema}/{stream_table}/{YYYY}_{MM}_{DD}/
    target_options:
      file_max_rows: 400000 # will split files into folder
```

**Comment by flarco** [comment]
Hi yes, should work, try as below.


```yaml
# env.yaml

connections:
  S3_LAKE_ZONE_A:
    type: s3

# this sets environment variables in sling process
variables:
  path_prefix: /dev-binoy/elt/data_landing
```

```yaml
# replication.yaml

source: MY_MYSQL
target: S3_LAKE_ZONE_A

defaults:
  object: {path_prefix}/{stream_schema}/{stream_table}/{YYYY}_{MM}_{DD}.parquet < - Use Path Prefix ?
  target_options:
    format: parquet

streams:

  # all tables in schema, except "forbidden_table"
  my_schema.*:
    object: {stream_schema}/{stream_table}/{YYYY}_{MM}_{DD}/
    target_options:
      file_max_rows: 400000 # will split files into folder

env:
  # ${path_prefix} pulls from environment variables in sling process or env
  path_prefix: '${path_prefix}'
```
