### ISSUE TITLE
Replicating a folder of CSV files to a database doesn't create expected {stream_file_name}

### ISSUE THREAD

**Issue by johnoscott** [slingdata-io/sling-cli#100]
I have a folder full of CSV files that i want to load into a database schema where each file name is the db table name.

```
./csv
├── marketo
│   ├── addresses.csv
│   ├── campaigns.csv
│   ├── contacts.csv

```

e.g. `addresses.csv` should load into table `addresses`

> file: `csv_load_fails.yml`
```yaml
source: 'local://'
target: POSTGRES

defaults:
  mode: full-refresh
  object: marketo.{stream_file_name}
  source_options:
    format: csv

streams:
  "file://./csv/marketo/": # folder of CSV files
    object: marketo.{stream_file_name}
    source_options:
      format: csv
```

when i run sling from the command line with this config file :

```
❯ sling run --replication  ./csv_load_fails.yaml
9:42PM INF Sling Replication [1 streams] | local:// -> POSTGRES

9:42PM INF [1 / 1] running stream file://./csv/marketo/
9:42PM INF connecting to target database (postgres)
9:42PM INF reading from source file system (file)
9:42PM INF writing to target database [mode: full-refresh]
9:42PM INF streaming data
9:42PM INF execution failed
9:42PM ERR  error="context canceled\n\n~ could not close statement\npq: extra data after last expected column\n\n~ could not insert into \"marketo\".\"marketo\".\ncontext canceled\n\n~ could not close statement\npq: extra data after last expected column"

9:42PM INF Sling Replication Completed in 1 secs | local:// -> POSTGRES

fatal:
~ 
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
~ execution failed
context canceled

~ could not close statement
pq: extra data after last expected column

~ could not insert into "marketo"."marketo".
context canceled

~ could not close statement
pq: extra data after last expected column

```

I am not sure that `{stream_file_name}` is being set correctly in my `object` definition.

And even if it was, I expect it would resolve to the file name including the extension (with `.` replaced with `_`) which would create a table name `addressses_csv` which is not what i want.

So there seem to a couple of things needed here:

1. a way to create a stream per file in a folder
2. a way to use the file name without the extension as the table name.
3. (and while i am at it) a way to target a schema name based on the source folder name (e.g. `marketo` above). I tried {stream_folder} but that didnt work (it gave me the parent folder `_csv_`

It seems like the current support for a folder of local files is intended to target a single db table. This makes sense if very large tables have their data split amongst many files.

**Comment by flarco** [comment]
Hi, the way you are running, it expects the same number of columns in all the files in the folder.

So you'll have to put a new stream for each file, if they have different structures.

e.g.;

```yaml
source: 'local://'
target: POSTGRES

defaults:
  mode: full-refresh
  object: marketo.{stream_file_name}
  source_options:
    format: csv

streams:
  "file://./csv/marketo/addresses.csv":
  "file://./csv/marketo/campaigns.csv":
  "file://./csv/marketo/contacts.csv":
```

**Comment by flarco** [comment]
About your second question, there isn't a way without the file extension. I think we'll add that actually in next release, that's a good idea.
The name string is cleaned up to conform with table naming (see [here](https://github.com/slingdata-io/sling-cli/blob/bb455a28a949791a56f9bf815939cc16766a1151/core/sling/config.go#L598-L605))

**Comment by johnoscott** [comment]
( I edited my issue ; added 3.)

**Comment by flarco** [comment]
Can you try again with the new replication YAML? The parent was indeed `csv` since you fed it a folder.

**Comment by johnoscott** [comment]
yes the tables are populated when i list a stream per csv file ( in the yaml you suggested above) however the table names have the csv file extension which i dont want:

schema: marketo
├── addresses_csv
├── campaigns_csv
└── contacts_csv

**Comment by flarco** [comment]
cool, that's an easy fix for next release (https://github.com/slingdata-io/sling-cli/pull/99). Should be released soon. For now, you can manually specify the object name for each stream.

**Comment by johnoscott** [comment]
I think this is a common use-case that would be create to support. Here is my suggestion:

```yaml
# suggested support for load a folder of csv files to a database, creating tables based on the file name (without the csv extension) 

source: 'local://'
target: POSTGRES

defaults:
  mode: full-refresh
  object: '{stream_file_folder}.{stream_file_name}'
  source_options:
    format: csv

streams:
  "file://./csv/marketo/*.csv":    # to schema: marketo
  "file://./csv/salesforce/*.csv": # to schema: salesforce
```

**Comment by flarco** [comment]
Yes I agree, was thinking along the same.

**Comment by johnoscott** [comment]
Glob expressions would be ideal here because they are more expressive than wildcards.

**Comment by johnoscott** [comment]
Related to this, i found it confusing that I can *discover* a stream per file in a local file connector 

> `~/.sling/env.yaml`
```yaml
 LOCAL_CSV:
    type: local
    url: file://./csv/
```


```bash
sling conns discover LOCAL_CSV --folder file://./csv/marketo
10:16PM INF Found 3 streams:
 - ./csv/marketo/addresses.csv
 - ./csv/marketo/campaigns.csv
 - ./csv/marketo/contacts.csv

```
