### ISSUE TITLE
S3 to Snowflake: Non-deterministic number of records streaming from folder of JSON files

### ISSUE THREAD

**Issue by nicklausroach** [slingdata-io/sling-cli#101]
When attempting to stream a folder of JSON files from S3 to Snowflake, a seemingly random, small subset of records are streamed while the rest are not. 

Task yaml:

```
source:
  conn: AWS_S3
  stream: /entries/
  primary_key: [id]
  update_key: date
  options:
    format: json
    flatten: true


target:
  conn: SNOWFLAKE
  object: load.entries
  options:
    column_casing: snake

mode: full-refresh
```

Running `sling run -c task.yaml` will stream anywhere from 30 to 150 of the 4000 records in the directory with seemingly no overt failure message.

The data are JSON files with file name YYYY-MM-DD.json for every day from 2023-10-19 to today. 

General format of the JSON data:
```
[
    {
        "Id": 295,
        "Name": "Description of some event",
        "Type": "VideoPlaybackStopped",
        "Date": "2023-10-28T20:42:21.8815348Z",
        "UserId": "cacd28457c174151ba6133b11ecd6008",
        "Severity": "Information"
    },
    {
        "Id": 294,
        "Name": "Description of some other event,
        "Type": "VideoPlayback",
        "Date": "2023-10-28T20:26:29.2277072Z",
        "UserId": "cacd28457c174151ba6133b11ecd6008",
        "Severity": "Information"
    },
]
```

There are some events that include a "shortOverview" field that usually just includes an IP address when the field is present.

[Results of a task run with debug flag.](https://github.com/slingdata-io/sling-cli/files/13866051/debug.txt)
