### ISSUE TITLE
Truncate Cascade

### ISSUE THREAD

**Issue by dluftspring** [slingdata-io/sling-cli#15]
The truncate strategy should optionally allow a cascade option so that the replication doesn't break in the presence of foreign key constraints or other table dependencies

**Comment by flarco** [comment]
I'm thinking you can use the `pre_sql` option in target options. 

Could you try that?

```yaml
source: SNOWFLAKE_DEV
target: DOCKER_POSTGRES

defaults:
  mode: truncate

streams:
  snowflake_schema.snowflake_table:
    object: public.my_postgres_table
    target_options:
      pre_sql: |
         truncate table public.my_postgres_table cascade;
```

**Comment by flarco** [comment]
The only problem I see with this is the lack of rollback. If there is an error, the target table will stay truncated, since the `pre-sql` runs before the transfer into the temp table... see here: https://github.com/slingdata-io/sling-cli/blob/main/core/sling/task_run_write.go#L117-L129
Actually, that should be changed, the `pre-sql` should run *after* the data is successfully inserted into the `temp table`, and before the temp data is put into the final temp.

**Comment by flarco** [comment]
Will change that. Also will add variable templating like https://docs.slingdata.io/sling-cli/replication#object-pattern-options

Like this, you do:

```yaml
source: SNOWFLAKE_DEV
target: DOCKER_POSTGRES

defaults:
  mode: truncate
  target_options:
    pre_sql: 'truncate table {target_schema}.{target_table} cascade;'

streams:
  snowflake_schema.snowflake_table:
    object: public.my_postgres_table
```

**Comment by dluftspring** [comment]
That's awesome! Thanks for following up about these feature requests

**Comment by flarco** [comment]
This should be good now in the new version here: https://github.com/slingdata-io/sling-cli/releases/tag/v1.0.31
Let me know if that works.

**Comment by dluftspring** [comment]
Is there a`--debug` flag I can pass? It's hard for me to tell what's being executed for `pre_sql` and I don't want to say it doesn't work without verifying but my testing with the 1.0.31 binary is still throwing the same error - specifically that I can't truncate a table referenced by a foreign key constraint

**Comment by dluftspring** [comment]
Okay I think the issue is postgres won't actually let you run a truncate statement when a target table contains a foreign key reference so my theoretical solution is this

```yaml
source: SNOWFLAKE_DEV
target: POSTGRES

defaults:
  mode: truncate
  object: '{target_schema}.{stream_schema}_{stream_table}'

streams:
  snowflake.source_table
    source_options:
      transforms: [ decode_latin1 ]
    target_options:
      pre_sql: 'truncate {target_schema}.{target_table} cascade;'
    mode: incremental
    primary_key: id
    object: 'public.postgres_table'
```

My idea here is to perform an incremental insert with an empty table this why we don't try to truncate but we know by the execution of the `pre_sql` that the target table and dependent objects will be truncated

But this throws a parsing error

```bash
fatal:
~ 
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
~ Error parsing replication config
~ Error parsing replication config
~ could not parse 'streams'
~ could not unmarshal
sling.ReplicationStreamConfig.PrimaryKey: []string: decode slice: expect [ or n, but found ", error found in #10 byte of ...|ary_key":"id"}}|..., bigger context ...|emental","object":"public.license","primary_key":"id"}}|...
```

**Comment by flarco** [comment]
Hey, there is a debug flag `-d`. To see a more verbose debugging, actually, pass in `DEBUG=LOW`.

The error is about the primary key, I can see how that's not clear, will try to improve that error message. `primary_key` needs to be an array. so pass in `primary_key: [id]`

Also, you can push up the `source_options.transforms` to the `defaults` section (so that it gets applied to all streams). That is, if you want.

```yaml
source: SNOWFLAKE_DEV
target: POSTGRES

defaults:
  mode: truncate
  object: '{target_schema}.{stream_schema}_{stream_table}'
  source_options:
    transforms: [ decode_latin1 ]

streams:
  snowflake.source_table:
    mode: incremental # overrides `mode: truncate`
    primary_key: [id]
    target_options:
      pre_sql: 'truncate {target_schema}.{target_table} cascade;'
    object: 'public.postgres_table' # overrides the `object: '{target_schema}.{stream_schema}_{stream_table}'`
```

**Comment by dluftspring** [comment]
I think there may be some more quoting config parsing issues related to #14 

For example I'm unable to map quoted columns using the `columns` option and i'm also not able to specify any incremental configs if the Snowflake columns are quoted. For example

`primary_key: sourceId` gets interpreted as SOURCEID and then throws an error.

I also had a separate question about how to map snowflake types to postgres user defined types but let me know if that needs a separate issue to keep the thoughts organized

**Comment by flarco** [comment]
OK, I've tested it with `primary_key: 'sourceId'` and it should work.
I've uploaded new binaries here: https://github.com/slingdata-io/sling-cli/releases/tag/v1.0.31
Could you give it a go and let me know?

About the `columns` mapping, yes, actually this only gets picked up when the source column type cannot be obtained (e.g. for File sources). For database sources, we get the column type from the driver, so this gets ignored. To change type, you can just cast on source database side, or transform downstream on target database. I've just added a note in the docs about this, hopefully that makes sense.

**Comment by dluftspring** [comment]
> To change type, you can just cast on source database side, or transform downstream on target database. I've just added a note in the docs about this, hopefully that makes sense.

I'll check the docs but I'm just not exactly sure how to force the type casting to happen in the temporary table creation - specifically when the types are user defined in the target database because things like Postgres enums don't map conveniently to data warehouse types

**Comment by flarco** [comment]
Yea, that's not going to work, cause the Postgres columns type are mapped from the source column type (snowflake).  There are 2 mappings used when sling moves data, one to convert from [Native to General types](https://github.com/flarco/dbio/blob/main/database/templates/types_native_to_general.tsv) (in source), and another from [General to Native types](https://github.com/flarco/dbio/blob/main/database/templates/types_general_to_native.tsv) (in target)
. 
For custom types casting, it brings complication across different databases, so not way if I want to try to get that working right now.

I'm thinking, would having Sling write to a separate table first, then using the `post_sql` to insert into the final table with custom types work?

**Comment by dluftspring** [comment]
Totally fair - it's a pretty specific issue. I think `post_sql` could work I also see you expose a `table_ddl` target option but i'm a bit fuzzy on exactly what behaviour that is overriding - is it just the final insert? Is it the temp table creation? Both?

**Comment by flarco** [comment]
It's both. See here: https://github.com/slingdata-io/sling-cli/blob/main/core/sling/task_run_write.go#L142
When creating the tmp table, it attempts to replace the final table name (`object`), in the DDL, to a temp table name. So make sure that matches. Would be good to specify `table_tmp` name as well.
That's true, give that a shot, I actually forgot about that flag because I don't use it much. It's a bit tedious to have to write DDLs manually, which is the whole reason Sling exists :D.
Make sure to use the `-d` flag for DEBUG mode to see all the SQL queries being executed as the task progresses, should help a bunch to see why errors occur.

**Comment by flarco** [comment]
@dluftspring good to close this?

**Comment by dluftspring** [comment]
Yes! Thanks for all the help

**Comment by jvyoralek** [comment]
Hi, I have similar needs, but I am not able to use mentioned solution for **PostgreSQL** cascade truncate table as in my case it will generate two SQL statements when `model: truncate` + `pre_sql`, where the second fails due error: `cannot truncate a table referenced in a foreign key constraint`

```
2024-03-14 18:33:50 DBG truncate table mapper.event cascade
2024-03-14 18:33:50 DBG truncate table "mapper"."event"
```

Is there any way how to have only one `truncate table` statement with `cascade` for postgresql?

`replication.yaml` file:

```
source: POSTGRES_DB_MAPPER_DEV_TEST
target: POSTGRES_DB_APP_TEST_REPL

defaults:
  mode: truncate
  object: '{target_schema}.{stream_table}'
  primary_key: [id]

  target_options:
    add_new_columns: false
    pre_sql: |
      truncate table {target_schema}.{target_table} cascade;

streams:
  mapper.event:
```

Log from run `sling run -r ./replication_mapper.yaml -d`:

```
2024-03-14 18:33:44 INF Sling Replication [1 streams] | POSTGRES_DB_MAPPER_DEV_TEST -> POSTGRES_DB_APP_TEST_REPL

2024-03-14 18:33:44 INF [1 / 1] running stream mapper.event
2024-03-14 18:33:44 DBG Sling version: 1.1.13 (linux amd64)
2024-03-14 18:33:44 DBG type is db-db

...

2024-03-14 18:33:50 DBG select count(*) cnt from "mapper"."event_tmp"
2024-03-14 18:33:50 INF executing pre-sql
2024-03-14 18:33:50 DBG truncate table mapper.event cascade
2024-03-14 18:33:50 DBG truncate table "mapper"."event"
2024-03-14 18:33:50 DBG drop table if exists "mapper"."event_tmp"
2024-03-14 18:33:50 DBG table "mapper"."event_tmp" dropped
2024-03-14 18:33:50 INF execution failed

2024-03-14 18:33:51 INF Sling Replication Completed in 6 secs | POSTGRES_DB_MAPPER_DEV_TEST -> POSTGRES_DB_APP_TEST_REPL | 0 Successes | 1 Failures


fatal:
--- sling_cli.go:384 func1 ---
--- sling_cli.go:430 cliInit ---
--- cli.go:284 CliProcess ---
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--- sling_logic.go:195 processRun ---

--------------------------- mapper.event ---------------------------
~ execution failed
--- task_run.go:98 func1 ---
~ Could not WriteToDb
--- task_run.go:520 runDbToDb ---
~ Could not truncate table: "mapper"."event"
--- task_run_write.go:444 WriteToDb ---
~ Could not execute SQL
--- database.go:1179 Exec ---
~ Error executing query [tx: true]
--- database.go:1210 ExecContext ---
~ Error executing: truncate table "mapper"."event"
--- transaction.go:135 ExecContext ---
pq: cannot truncate a table referenced in a foreign key constraint
```
