### ISSUE TITLE
Concurrent sling tasks 

### ISSUE THREAD

**Issue by Codykilpatrick** [slingdata-io/sling-cli#164]
Hey again! Once again thanks for the killer product! I was wondering if its possible to have multiple sling tasks dumping into one table for example:
```
{
  "source": {
    "conn": "mysql_connection_string",
    "stream": "SELECT val_1, val_2, val_3 FROM my_table WHERE {incremental_where_cond} AND id IN (1, 3, 5, 7, 9, 11, 13, 15);",
    "primary_key": "id",
    "update_key": "date",
    "options": {}
  },
  "target": {
    "conn": "postgresql_connection_string",
    "object": "my_postgres_table_1",
    "options": {}
  },
  "mode": "incremental"
}
```
```
{
  "source": {
    "conn": "mysql_connection_string",
    "stream": "SELECT val_1, val_2, val_3 FROM my_table WHERE {incremental_where_cond} AND id IN (2, 4, 8, 10, 12, 14);",
    "primary_key": "id",
    "update_key": "date",
    "options": {}
  },
  "target": {
    "conn": "postgresql_connection_string",
    "object": "my_postgres_table_1",
    "options": {}
  },
  "mode": "incremental"
}
```
The goal would be to have these two tasks running simultaneously on an infinite loop, but I ran into some errors when I tried it. Is this something that is/could be possible?

**Comment by flarco** [comment]
Hi Cody, for sure, this should be possible. Do you mind sharing your debug level output/error?

**Comment by Codykilpatrick** [comment]
So the logs get a little messy but here are the two errors it runs into regularly:
```
fatal:
~ 
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
~ 
~ execution failed
~ Could not WriteToDb
~ could not create temp table "forerunner_public"."bearing_time_record_staging_tmp"
~ Error creating table "forerunner_public"."bearing_time_record_staging_tmp"
~ Could not execute SQL
~ Error executing [tx: false] create table if not exists "***_public"."bearing_time_record_staging_tmp" ("heading" integer,
"bearing_time_configuration" text,
"date" bigint,
"id" integer,
"hex_representation" text,
"typekey" integer)
pq: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
```
```
fatal:
~ 
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
~ 
~ execution failed
~ Could not WriteToDb
inserted in temp table but table count (0) != stream count (1197). Records missing. Aborting
```

This bash script is how I am handling the "concurrent" sling tasks:
```
while true; do
    docker run --network=forerunner-network --rm -v "$SCRIPT_DIR/btr-1-task.json:/btr-1-task.json" -i slingdata/sling:v1.0.68 run -d -c btr-1-task.json &
    docker run --network=forerunner-network --rm -v "$SCRIPT_DIR/btr-2-task.json:/btr-2-task.json" -i slingdata/sling:v1.0.68 run -c btr-2-task.json &&
    fg
done
```

**Comment by flarco** [comment]
Interesting 🤔 
Looking at [this](https://stackoverflow.com/questions/21706858/org-postgresql-util-psqlexception-error-could-not-serialize-access-due-to-read) looks like there isn't an easy fix.

Another idea, why not use a [replication](https://docs.slingdata.io/sling-cli/run/configuration#replication-config)?

It accepts JSON config as well, and you can specify 2 custom SQL streams. Difference it there will run one after then after, sequentially, and not interfere.

```yaml

source: mysql_connection_string
target: postgresql_connection_string

defaults:
  object: my_postgres_table_1
  mode: incremental
  primary_key: id
  update_key: date

streams:
  btr-1-task:
    sql: 'SELECT val_1, val_2, val_3 FROM my_table WHERE {incremental_where_cond} AND id IN (1, 3, 5, 7, 9, 11, 13, 15)'
  btr-2-task:
    sql: 'SELECT val_1, val_2, val_3 FROM my_table WHERE {incremental_where_cond} AND id IN (2, 4, 8, 10, 12, 14)'


```
