### ISSUE TITLE
Sling support of array data type

### ISSUE THREAD

**Issue by flarco** [slingdata-io/sling-cli#179]
### Discussed in https://github.com/slingdata-io/sling-cli/discussions/178

<div type='discussions-op-text'>

<sup>Originally posted by **matanper** February 19, 2024</sup>

I try to copy between 2 postgres databases a table with array of uuid, and I get warning `WRN using string since type '_uuid' not mapped for col 'foo': ""`
It still copies the data as varchar column, however if the array is too large I get `pq: value too long for type character varying(255)`

code to reproduce:
```sql
create table test_table  (
	"id" uuid,
	"foo" _uuid
);

INSERT INTO test_table (id, foo) VALUES (gen_random_uuid(), ARRAY[gen_random_uuid(), gen_random_uuid()]);
```

```yaml
source: LOCAL_PG
target: LOCAL_PG

defaults:
  mode: full-refresh 
  object: 'test.{stream_table}'

streams:
  public.test_table:
```

**Comment by flarco** [comment]
@matanper fixed in https://github.com/slingdata-io/sling-cli/pull/173, added new mapping for `_uuid` to `JSON` type.
Releasing soon, closing.

**Comment by flarco** [comment]
Actually, the array is not formatted correctly when selecting from Postgres, need to fix that.

As a workaround, just cast the column as `text`:

```yaml
source: LOCAL_PG
target: LOCAL_PG

defaults:
  mode: full-refresh 
  object: 'test.{stream_table}'

streams:
  public.test_table:
    source_options:
      columns:
        foo: text  # this will cast foo as text instead of json
```
