### ISSUE TITLE
Why can't replication target work with {stream_schema}.{stream_table}

### ISSUE THREAD

**Issue by alberttwong** [slingdata-io/sling-cli#221]
```
atwong@Albert-CelerData ~ % cat replication.yaml
source: DUCKDB
target: STARROCKSLOCAL

# default config options which apply to all streams
defaults:
  mode: full-refresh
  object: {stream_schema}.{stream_table}

streams:
  main.*:
```
```
atwong@Albert-CelerData ~ % sling run -r ./replication.yaml
fatal:
~ Error parsing yaml content
yaml: line 6: did not find expected key
```

**Comment by alberttwong** [comment]
this works
```
atwong@Albert-CelerData ~ % cat replication.yaml
source: DUCKDB
target: STARROCKSLOCAL

# default config options which apply to all streams
defaults:
  mode: full-refresh
  object: main.{stream_table}

streams:
  main.*:
```
