### ISSUE TITLE
MongoDB:  Select is not selecting / excluding columns 

### ISSUE THREAD

**Issue by comino** [slingdata-io/sling-cli#244]
## Issue Description

- Description of the issue: 
Select in comb. with mongoDB doesnt select the keys 

- Sling version (`sling --version`):  
1.2.2

- Operating System (`linux`, `mac`, `windows`):  
linux

- Replication Configuration: 

```yaml
source: MONGO
target: CLICKHOUSE

default: 
  mode: full-refresh
  
streams:
  mydb.users: 
    mode: full-refresh
    object: 'mongo_users'
    select: ['email', "_id" ]
```

- Log Output (please run command with `-d`): 

```
2:19PM INF execution succeeded
```

But the resulting dataset contains the whole user object.
I also tried the reverse approach and excluded fields with "-password", but the dataset still contains the password column.
