### ISSUE TITLE
Sling crashes when migrating table from postgres to s3

### ISSUE THREAD

**Issue by giqua** [slingdata-io/sling-cli#268]
## Issue Description
- Description of the issue: 
Hi, I'm trying to migrate data from Postgres DB to a local instance of s3 emulated by localstack. I tried with a table with 30k rows and the migration was completed correctly but when I try to migrate a table with 3.5 million records the app crashes due to [signal SIGSEGV: segmentation violation code

- Sling version (`sling --version`): 
1.2.5
- Operating System (`linux`, `mac`, `windows`): 
linux
- Replication Configuration: 

```yaml
# replication.yaml

source: READ_ONLY_PG
target: LOCALSTACK_S3

defaults:
  mode: incremental
  primary_key: [id]
  object: "s3://bucket/{stream_table}/*.parquet"
  target_options:
    format: parquet
    file_max_rows: 100000
  # source_options:
  #     limit: 1000

streams:
  # all tables in schema, except "forbidden_table"
  # public.*:
  #   object: "{stream_schema}/{stream_table}/{YYYY}_{MM}_{DD}/*.parquet"
  #   primary_key: [id]
  #   target_options:
  #     file_max_rows: 400000 # will split files into folder
  # public.forbidden_table:
  #   disabled: true  

  public.*:
    object: "s3://bucket/{stream_table}/*.parquet"
    primary_key: [id]
    target_options:
      file_max_rows: 100000 # will split files into folder
      format: parquet
    mode: incremental
  
  public.alembic_version:
    disabled: true
  
  public.article:
    disabled: true
  
  public.failedarticle:
    disabled: false
  ...
```

- Log Output (please run command with `-d`): 

```
Log attached to the issue due to body too long
```
[log.txt](https://github.com/slingdata-io/sling-cli/files/15023831/log.txt)
