### ISSUE TITLE
OpenID Authentication to BigQuery on GitHub Action

### ISSUE THREAD

**Issue by mik-laj** [slingdata-io/sling-cli#288]
## Issue Description

- Description of the issue: 

Hi. I'm migrating from my  Python script that replicated data from Postgres to BigQuery to Sting, but I ran into a problem authenticating to BigQuery. Before migrating, my workflow authenticated to BigQuery, but now when I run Sling it raises error:
```
~ Failed to get datasets in project: pola-bi-looker
Get "https://bigquery.googleapis.com/bigquery/v2/projects/pola-bi-looker/datasets?all=false&alt=json&pageToken=&prettyPrint=false": oauth2/google/externalaccount: invalid response when retrieving subject token: Get "https://pipelinesghubeus2.actions.githubusercontent.com/tbxRzkEOIWLXAKSf1wWOGhUMoEfjMwfVc97IR1ADJONKVKyKn0/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/c1c29e0b-3a29-4cb1-ac66-b704bba0d36d/jobs/ffcfb67d-d2df-5907-4b20-d6b205d37b70/idtoken?api-version=2.0&audience=https%3A%2F%2Fiam.googleapis.com%2Fprojects%2F354540873199%2Flocations%2Fglobal%2FworkloadIdentityPools%2Fgithub%2Fproviders%2Fpola-backend-repo": context canceled
```
I checked that the gcloud sdk still has access to GCP, so it is not a problem on the GCP side.

I even tried to update some golang libraries, but it didn't help.
```yaml
      - name: Set up GoLang
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          cache: false

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          repository: slingdata-io/sling-cli
          path: sling

      - run: |
          cd sling
          go mod edit -dropreplace='github.com/flarco/g' go.mod
          go mod edit -dropreplace='github.com/slingdata-io/sling' go.mod
          go mod edit -droprequire='github.com/slingdata-io/sling' go.mod
          go mod tidy
          go get -u golang.org/x/oauth2
          go get -u cloud.google.com/go
          go get -u cloud.google.com/go/bigquery
          go get -u cloud.google.com/go/bigtable
          go get -u cloud.google.com/go/storage
          go build -o /usr/local/bin/sling cmd/sling/*.go
          cd ..
```

- Sling version (`sling --version`):  1.2.9

- Operating System (`linux`, `mac`, `windows`): linux

- Replication Configuration: 

```yaml
source: MY_POSTGRES
target: MY_BIGQUERY

defaults:
  mode: full-refresh
  object: '{target_schema}.raw__{stream_table}'
  primary_key: [id]

streams:
  public.ai_pics_aiattachment:
  public.ai_pics_aipics:
  public.bi_*:
    primary_key: []
  public.company_brand:
  public.company_company:
  public.gpc_*:
  public.pola_query:
    mode: incremental
    update_key: id
  public.pola_searchquery:
  public.pola_stats:
  public.product_product:
  public.report_attachment:
  public.report_report:
  public.users_user:
    select: ["-password"]

env:
  # Adds the _sling_loaded_at timestamp column
  SLING_LOADED_AT_COLUMN: true

  # Allows create empty tables
  SLING_ALLOW_EMPTY: TRUE
```

- Log Output (please run command with `-d`): 

```
$ sling conns set MY_BIGQUERY \
  type=bigquery \
  project="${GCP_PROJECT_ID}" \
  dataset="${GCP_BIGQUERY_DATASET}" \
  gc_bucket="${GCP_BUCKET_NAME}" \
  location="${GCP_REGION}"
2:06AM INF connection `MY_BIGQUERY` has been set in /home/runner/.config/.sling/env.yaml. Please test with `sling conns test MY_BIGQUERY`
$ sling conns test MY_BIGQUERY   
~ Failed to get datasets in project: pola-bi-looker
Get "https://bigquery.googleapis.com/bigquery/v2/projects/pola-bi-looker/datasets?all=false&alt=json&pageToken=&prettyPrint=false": oauth2/google/externalaccount: invalid response when retrieving subject token: Get "https://pipelinesghubeus2.actions.githubusercontent.com/XXXXXXXX/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/XXXXXXX/idtoken?api-version=2.0&audience=https%3A%2F%2Fiam.googleapis.com%2Fprojects%2F354540873199%2Flocations%2Fglobal%2FworkloadIdentityPools%2Fgithub%2Fproviders%2Fpola-backend-repo": context canceled
```
