### ISSUE TITLE
Reshift ,

### ISSUE THREAD

**Issue by matanper** [slingdata-io/sling-cli#305]
## Issue Description

- Description of the issue: 

- Sling version (`sling --version`): 

- Operating System (`linux`, `mac`, `windows`): 

- Replication Configuration: 

```yaml
source: <source>
target: <target>
streams:
  ...
```

- Log Output (please run command with `-d`): 

```
Paste log here.
```
