### ISSUE TITLE
Cannot use wildcard with CSV files in Azure Blob Storage

### ISSUE THREAD

**Issue by kristianandre** [slingdata-io/sling-cli#314]
## Issue Description

- Description of the issue: 

I have tried to follow the examples [here](https://docs.slingdata.io/sling-cli/run/examples/file-to-database) using Azure Blob Storage as the source and DuckDB as the target. However, when using the `*.csv` glob pattern, I got the following message:
```
WRN Did not match any streams. Exiting.
```
I have double checked that it works when referencing a specific csv, e.g., `container_name/folder_name/file.csv` file or when I reference a "directory" such as `container_name/folder_name/`. I have also made sure that the SAS token has read and list permissions.

I know fsspec had a pretty recent change in how it treats glob ([here](https://github.com/fsspec/adlfs/commit/01e91b150b7d4e6793d882b0e700b8966b181f95) is the changelog for adlfs). I am guessing that is unrelated.

- Sling version (`sling --version`): 
1.2.10
- Operating System (`linux`, `mac`, `windows`): 
`mac`
- Replication Configuration: 

```yaml
source: AZURE_BLOB_STORAGE
target: DUCKDB

defaults:
  mode: full-refresh
  object: 'target_schema.{stream_file_folder}_{stream_file_name}'
  source_options:
    format: csv

streams:
  "folder_name/*.csv":
```

- Log Output (please run command with `-d`): 

```
WRN Did not match any streams. Exiting.
```
