### ISSUE TITLE
Column type coercion to boolean from tinyint stopped working in 1.2.10

### ISSUE THREAD

**Issue by somiandras** [slingdata-io/sling-cli#320]
## Issue Description

I have a couple of boolean columns in a MySQL source defined as `tinyint` that I coerced into `bool` in my Postgres target using `source_options`, but this seems to have stopped working after upgrading to 1.2.10. (worked on 1.2.9 and doesn't work on either 1.2.10 or 1.2.11)

- Description of the issue: 

In my replication config I'm adding source options to the MySQL source tables like this:

```
    source_options:
      columns:
        myFirstColumn: bool
        mySecondColumn: bool
        myThirdColumn: bool
```

These columns are TINYINT in MySQL, containing 0, 1 and possibly NULL as values. Columns were correctly coerced to boolean in my Postgres target before 1.2.10, now they are VARCHAR(65500).

- Sling version (`sling --version`):  1.2.11 

- Operating System (`linux`, `mac`, `windows`):  linux (docker)

- Replication Configuration: 

can't share the full config, the defaults are pretty simple, everything is set up on stream level

```yaml
defaults:
  object: staging.{stream_table}

  target_options:
    column_casing: snake

...
```

- Log Output (please run command with `-d`): 

```
Paste log here.
```
