### ISSUE TITLE
Sling issue while inserting data into StarRocks using Parquet Format.

### ISSUE THREAD

**Issue by pawan-chauhan-9560** [slingdata-io/sling-cli#325]
## Issue Description

- privateIp :- FE_Url
- Description of the issue:  Using a  parquet file, 4125 events available. Getting dataflow issue dial tcp **privateIP**:8040: connect: connection refused

context canceled

- Sling version 1.2.11 

- Operating System linux

- Replication Configuration: 

```yaml
source:  Parquet file ( Created from sql server)
target: Starrocks
streams:
  ./sling run --src-stream 'file:///opt/sling/fastest/*.parquet' --tgt-conn STARROCKS --tgt-object testing.Product' --mode full-refresh
```

- Log Output (please run command with `-d`): 

```
~ could not perform request
Put "http://test:***@privateIP:8040/api/testing/FastestGrowingHSProducts_3_tmp/_stream_load": dial tcp **privateIP**:8040: connect: connection refused

context canceled

~ error writing dataflow to local storage: /tmp/starrocks/testing/Product_3_tmp/2024-06-17T083727.126
~ could not perform request
Put "http://test:***@privateIP:8040/api/testing/Product_3_tmp/_stream_load": dial tcp **privateIP**:8040: connect: connection refused

```
