### ISSUE TITLE
Null Timestamp Stored as 1970-01-01 in Parquet Output File

### ISSUE THREAD

**Issue by karhendana** [slingdata-io/sling-cli#329]
## Issue Description

- Description of the issue: 
When exporting PostgreSQL timestamp column with null values to parquet files, the resulting column is filled with arbitrary value '1970-01-01'

- Sling version (`sling --version`): 
1.2.11

- Operating System (`linux`, `mac`, `windows`): 
linux

- Replication Configuration: 

```yaml
source: postgresql://.....
target: 'local://'

defaults:
  mode: full-refresh

streams:
  test_parquet:
    object: file:///tmp/test.parquet
    sql: |
      select null::timestamp with time zone as ts
```

- Log Output (please run command with `-d`): 

```
1:04PM INF Sling Replication [1 streams] | postgresql://.... -> local://

1:04PM INF [1 / 1] running stream test_parquet
1:04PM INF connecting to source database (postgres)
1:04PM INF reading from source database
1:04PM INF writing to target file system (file)
1:04PM INF wrote 1 rows [3 r/s] to file:///tmp/test.parquet
1:04PM INF execution succeeded

1:05PM INF Sling Replication Completed in 3s | postgresql://.... -> local:// | 1 Successes | 0 Failures
```

- Result:

```
$ duckdb -c "select * from '/tmp/test.parquet'"
┌──────────────────────────┐
│            ts            │
│ timestamp with time zone │
├──────────────────────────┤
│ 1970-01-01 00:00:00+00   │
└──────────────────────────┘
```
