### ISSUE TITLE
Transferring data using the Sling, source to destination works fine if the language is English, but if the language is different, it changes the data Current language is Arabic.

### ISSUE THREAD

**Issue by pawan-chauhan-9560** [slingdata-io/sling-cli#340]
## Issue Description

- Description of the issue: Transferring data using the Sling, source to destination works fine if the language is English, but if the language is different, it changes the data Current language is **Arabic**. (Source and Destination column datatype is nvarchar(max))

- Sling version : 1.2.13

- Operating System : Linux

- Replication Configuration: 

```yaml
source: SQL
target: SQL
streams:
/sling run --src-conn TestDB --src-stream 'dbo.appconfig' --tgt-object 'file:///opt/sling/appconfig/*.csv'

./sling run --src-stream 'file://opt/sling/appconfig/*.csv'  --src-options '{transforms: [remove_accents]}' --tgt-conn MY_TARGET_DB --tgt-object 'dbo.appconfig' --mode full-refresh
  ...
```

- Log Output (please run command with `-d`): 

data file for testing

[KazakhstanImport.xlsx](https://github.com/user-attachments/files/16392814/KazakhstanImport.xlsx)
