### ISSUE TITLE
there is something wrong with starrocks plugin

### ISSUE THREAD

**Issue by expressways** [slingdata-io/sling-cli#361]
## Issue Description

- Description of the issue: 
When connect starrocks ,return fatal:
cmd:
$ sling conns test starrocks

- Sling version (`sling --version`): 
Version: 1.2.15

- Operating System (`linux`,  `windows`): 

- Replication Configuration: 

```yaml
connections:
  starrocks:
      fe_url: http://0.0.0.0:8030
      url: starrocks://root:xxxxx@0.0.0.0:9030/tmp
```

- Log Output (please run command with `-d`): 

```
[mysql] 2024/08/20 11:32:50 connection.go:49: unexpected EOF
fatal:
~ could not connect to database
invalid connection

```
