### ISSUE TITLE
SFTP does not support 'diffie-hellman-group-exchange-sha256'

### ISSUE THREAD

**Issue by AashishMTech** [slingdata-io/sling-cli#365]
## Issue Description

- Description of the issue: getting error while connecting to sftp 
ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha256 diffie-hellman-group14-sha1 ext-info-c kex-strict-c-v00@openssh.com], server offered: [diffie-hellman-group-exchange-sha256

- Sling version (`sling --version`): 1.2.14

- Operating System (`linux`, `mac`, `windows`): linux

- Replication Configuration: 

```yaml
# replication.yaml

source: MY_SFTP
target: SNOWFLAKE

defaults:
  mode: truncate
  source_options:
    format: xml


streams:
  
  "sftp://host/IN/contract.xml":
    object: 'app_{USER_NAME}'
    single: true


 
env:
  SAMPLE_SIZE: 2000 # increase the sample size to infer types (default=900).
  SLING_STREAM_URL_COLUMN: true # adds a _sling_stream_url column with file path
  SLING_LOADED_AT_COLUMN: timestamp
  USER_NAME: '${USER_NAME}' 
  
  ...
```

- Log Output (please run command with `-d`): 

```
Paste log here.
ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha256 diffie-hellman-group14-sha1 ext-info-c kex-strict-c-v00@openssh.com], server offered: [diffie-hellman-group-exchange-sha256
```
