### ISSUE TITLE
Add incremental for Delta and Iceberg

### ISSUE THREAD

**Issue by flarco** [slingdata-io/sling-cli#369]
- [x] Add `IncrementalKey` and `IncrementalValue` to `filesys.FileStreamConfig`
- [x] Move `FileStreamConfig` into `iop` for `datastream` to use
- [x] Add tests

```yaml
source: aws_s3
target: postgres

streams:
  my/table:
    update_key: updated_dt
    primary_key: id
    obeject: my_schema.my_table
    

```
