### ISSUE TITLE
Mongodb arrays of object support

### ISSUE THREAD

**Issue by swapnil-paralkar783** [slingdata-io/sling-cli#383]
## Issue Description

We have to fetch arrays of object from one of our collections . We found that to do that we have to use $unwind in the aggregation pipeline . 

- Description of the issue: 

We are not able to pass the collection name in the --src-stream .  Also we did not find an option to pass the collection name in the yaml file .

Command :

sling run --src-stream "mongodb://test:password@localhost:27017/prototype_v1_01?pipeline=file:/C:\\Database\\mongodb\\Jira\\Sling\\test.yaml"

- Sling version (`sling --version`): 
1.2.19
- Operating System (`linux`, `mac`, `windows`): 
windows
- Replication Configuration: 

```yaml

test.yaml

   - $match:
        status: "Loaded"  # Collection has 'status' field
    - $unwind:
        path : "$audit"


streams:
  ...
```

- Log Output (please run command with `-d`): 

```
Paste log here.

7:34PM INF connecting to source database (mongodb)
7:34PM INF reading from source database
7:34PM INF execution failed
fatal:
~ Could not get source columns
could not query to get tables
