### ISSUE TITLE
Stricter CSV Reader

### ISSUE THREAD

**Issue by TimPossiblee** [slingdata-io/sling-cli#385]
## Feature Description

I would like to request the following improvements regarding CSV loading.

1. Fail on different number of columns per file

    When for example the delimiter is part of the data, different rows will have different amount of columns.
    I would like to have an option to Error when not every row has the same number of columns, instead of omitting or creating dummy columns.
    Different number of columns accross files should still be allowed.
    The expected number of columns should be taken from the csv header or first row of data.

2. Preserve raw values when column is defined as string

    I would expect sling to preserve the original value of a column when it is defined as string e.g. columns={"*": "string"}.
    But even with SAMPLE_SIZE=0 the analyzer still seems to be running on the first row of data.
    Disabling data sampling when set to 0 would also be an option.

    See how in the example in the first column in the first row is missing the whitespace.

3. SourceOptions.TrimSpace seems to be a no-op

    If I want to trim all whitespaces above the SAMPLE_SIZE value trim_space=true seems to have no effect. Specifying it as a transformation works, is this the intended way?

- Version: 1.2.20
- Operating System: `linux`
- Sample CSV:

```csv
col1;col2;col3
 col1_data ;col2_data;col3_data
 col1_data ;col2_data;with_delimiter;col3_data
 col1_data ;col2_data
```

- Replication Configuration:

```yaml
source: LOCAL
target: SNOWFLAKE

defaults:
  mode: full-refresh
  single: true

  source_options:
    format: csv
    header: true
    delimiter: ';'
    trim_space: true
    columns:
      "*": string

  target_options:
    column_casing: target

streams:
  "file://./test.csv":
    object: 'PUBLIC.CSV_TEST'

env:
  SLING_STREAM_URL_COLUMN: true
  SAMPLE_SIZE: 0
```

- Output in Snowflake:

|COL1|COL2|COL3|_SLING_STREAM_URL|
|----|----|----|-----------------|
|col1_data|col2_data|col3_data|file://./test.csv|
|\scol1_data\s|col2_data|with_delimiter|file://./test.csv|
|\scol1_data\s|col2_data|NULL|file://./test.csv|
