### ISSUE TITLE
Unable to discover FTPS streams

### ISSUE THREAD

**Issue by guaripete-github** [slingdata-io/sling-cli#398]
## Issue Description

- Description of the issue: Unable to discover FTPS streams

- Sling version (`sling --version`): 1.2.19

- Operating System (`linux`, `mac`, `windows`): windows

- env.yaml: 

```yaml
  URL__FTPS:
    url: "ftps://<username>:<password>@<host>"
```

- Log Output (please run command with `-d`): 

```
sling conns test URL__FTPS
10:34AM INF success!

sling conns discover URL__FTPS
fatal:
~ could not discover URL__FTPS (See https://docs.slingdata.io/sling-cli/environment)
Unhandled connection type: ftps
```
tried:

```yaml
  URL__FTPS:
    url: "ftps://<username>:<password>@<host>"
    ftps: true
```

with same result.

And also tried:

```yaml
  URL__FTPS:
    url: "ftp://<username>:<password>@<host>"
    ftps: true
```

```
sling conns test URL__FTPS   
fatal:
~ unable to connect to ftp server
EOF
```

**Comment by flarco** [comment]
This is the proper way to input: 
```
URL__FTPS:
    url: "ftp://<username>:<password>@<host>"
    ftps: true
```

Can you run with env var `DEBUG=TRUE`?

**Comment by guaripete-github** [comment]
Got: 

```
sling conns test URL__FTPS
DBG opened "ftp" connection (conn-ftp-GDN)
fatal:
~ unable to connect to ftp server
dial tcp <ip>:21: i/o timeout
```

I believe the server uses implicit FTPS (port 990) and not explicit FTPS (port 21)

Tried:

```
URL__FTPS:
    url: "ftp://<username>:<password>@<host>:990"
    ftps: true
```

```
DBG opened "ftp" connection (conn-ftp-X2j)
fatal:
~ unable to connect to ftp server
EOF
```

**Comment by flarco** [comment]
Don't think it will make a difference, but just to try... can you specify `type=ftp` `host`, `user`, `password`, `port` keys instead of `url`?

**Comment by guaripete-github** [comment]
Indeed, no difference:

```yaml
  URL__FTPS:
    type: ftp
    host: <host>
    user: <user>
    port: 990
    password: <password>
    ftps: true
```

```
DBG opened "ftp" connection (conn-ftp-GRx)
fatal:
~ unable to connect to ftp server
EOF
```
