### ISSUE TITLE
Bug when replicating NUMERIC columns from postgres to parquet

### ISSUE THREAD

**Issue by joconnor-ecaa** [slingdata-io/sling-cli#405]
## Issue Description

- Description of the issue: 

Were replicating postgres tables to parquet files in Google Cloud Storage using Dagster's sling integration. When replicating a table using NUMERIC types, the outputs are occasionally wrong come out wrong: specifically, their decimal place moves, e.g. 0.123456... becomes 12345.6...

After some experimentation we noticed that this happens only when the NUMERIC has a large number of digits after the decimal point. Casting to float or rounding to 

- Sling version (`sling --version`): 

1.2.20

- Operating System (`linux`, `mac`, `windows`): 

linux

- Replication Configuration: 

```yaml
source: POSTGRES_DB
target: GCS_BUCKET
streams:
  gs://bucket/file.pq:
    object: public.some_table
```

- Log Output (please run command with `-d`): 

I don't have this right now, will follow up when possible.
