### ISSUE TITLE
SQL SERVER regression due to issue 402

### ISSUE THREAD

**Issue by CharlesRngrd** [slingdata-io/sling-cli#415]
- Description of the issue: 

The fix for https://github.com/slingdata-io/sling-cli/issues/402 introduced a regression for me.

It seems that if the SQL Server is configured to use SQL Server authentication instead of Windows authentication, the `-T` flag won’t work.

As I'm using a service account that is not linked to the Active Directory plus the server instance is on-premise, I must use trust the server certificate plus send the credentials to BCP.

Instead of the `isTrusted` function, I suggest to add a `isBulkTrusted` connection parameter.

Ok for you @flarco and @pSpitzner ?

- Sling version:

`1.2.21`

- Operating System:

`Window`

- Connection Configuration: 

```yaml
connections:
  datalake_prod:
    type: sqlserver
    host: dlprod.cofaq.fr
    user: service-databi
    password: ****
    database: SLING
    port: 31435
    trust_server_certificate: true
```
- Log Output : 

```
~ could not bulk import
~ SQL Server BCP Import Command -> bcp 'dbo.BRAINDBM_BASEREF__conditions_tmp' in 'C:/Users/apautrot/AppData/Local/Temp/sqlserver.1729586398168.YlM1.csv' -S '****' -d 'SLING' -t ',' -m '1' '-w' -q -b '50000' -F '2' -e 'C:/Users/apautrot/AppData/Local/Temp/sqlserver.1729586398412.Epd.error' '-T'
SQL Server BCP Import Error  ->
SQLState = 28000, NativeError = 18452
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.
```
