### ISSUE TITLE
Login Fails with `*` in password

### ISSUE THREAD

**Issue by bmritz** [slingdata-io/sling-cli#42]
Hello, 

I tried to run `sling conns discover MY_SQLSERVER_DB`, but the command is failing with the error:

```
$ sling conns discover MY_SQLSERVER_DB
fatal:
~
~ could not discover MY_SQLSERVER_DB (See https://docs.slingdata.io/sling-cli/environment)
~ could not connect to MY_SQLSERVER_DB
~ could not connect to database
mssql: login error: Login failed for user 'britz'.
```

My ~/.sling/env.yaml looks like this:

```
connections:
  MY_SQLSERVER_DB:
    type: sqlserver
    url: 'sqlserver://britz:<pw-redacted>@<host-redacted>:1433/<db-redacted>'

variables: {}
```

My Password does have a `*` in it, and I _think_ that may be what is throwing things off. I believe this is the case because I tried another connection with a SQL Server Database, with a similar env.yaml, but my password in that database does not have a `*` in it, and that does work.

**Comment by flarco** [comment]
Hey there. Can you try with the `key`: `value` approach instead of URL?
See docs [here](https://docs.slingdata.io/connections/database-connections/sqlserver).

```yaml
connections:
  MY_SQLSERVER_DB:
    host: '<host>'
    user: 'britz'
    database: '<database>'
    password: '<password>'
    port: 1433
```
