### ISSUE TITLE
Add TLS Config for Clickhouse

### ISSUE THREAD

**Issue by flarco** [slingdata-io/sling-cli#420]
### Discussed in https://github.com/slingdata-io/sling-cli/discussions/419

<div type='discussions-op-text'>

<sup>Originally posted by **igrpon** October 24, 2024</sup>
How could I setup sling connection to clickhouse with SSL and server certificate.

Currently I have YAML config like this:

```
connections:
  DWH_CH:
    type: clickhouse
    host: host.net
    port: 8443
    database: prod-01
    user: root
    password: **********
    http_url: https://root@host.net:8443
```

But I got the following error:
```
fatal:
~ could not connect to database
clickhouse [dsn parse]: https without TLS
```</div>
