### ISSUE TITLE
sqlserver connection to server instance

### ISSUE THREAD

**Issue by nixent** [slingdata-io/sling-cli#43]
I'm trying to connect to a SQL server instance `Server01\Instance01` and getting error: `invalid character "\\" in host name`
Combined with Windows authentication I ended up with following config:
```
connections:
  mssql:
    type: sqlserver
    host: Server01\Instance01
    database: DB     
    schema: dbo
    user: DOMAIN%5Cuser01
    password: xxx
```
To test it out I have tried to connect with the same user config to another SQL server which is using default instance and it works fine.
How to connect to a specific SQL server instance?

**Comment by flarco** [comment]
Interesting, I thought that database = instance. Need to fix the URL generator [here](https://github.com/flarco/dbio/blob/main/connection/connection.go#L485).

Can you try config below and confirm? Just input the URL directly to override. Got the URL format from the 3rd party lib sling uses [here](https://github.com/denisenkom/go-mssqldb). You might need to [Query Escape](https://www.google.com/search?q=query+escape+online) your password if it has special characters.

```yaml
connections:
  mssql:
    type: sqlserver
    schema: dbo
    url: "sqlserver://DOMAIN%5Cuser01:password@ Server01/Instance01?database=DB&param2=value"
``` 

I can then apply the fix if that works.
