### ISSUE TITLE
Motherduck does not seem to use the passed `database`

### ISSUE THREAD

**Issue by hello-world-bfree** [slingdata-io/sling-cli#439]
## Issue Description

- Description of the issue: Despite setting a connection string or through `env.yaml` with a particular database that exists within Motherduck, Sling uses the default database, `my_db`. To be clear, the replication is successful. It's just replicated into the defualt database within Motherduck, `my_db` and not in the set database.

- Sling version (`sling --version`):  1.2.22

- Operating System (`linux`, `mac`, `windows`): mac

- Replication Configuration: 

`env.yaml`:

```yaml
connections:
  motherduck_hallow:
    type: motherduck
    database: hallow_replication
    duckdb_version: 1.1.3
    motherduck_token: {my_token}
```

Replication:

```yaml
source: hallow_staging
target: md_sling

defaults:

  source_options:
    empty_as_null: false

  target_options:
    column_casing: snake

streams:
  hallow.users:
    disabled: false
    mode: full-refresh
    object: main.hallow_staging_users
```
