### ISSUE TITLE
Azure storage connection stores files locally instead of Azure storage account

### ISSUE THREAD

**Issue by nixent** [slingdata-io/sling-cli#44]
I'm fetching data from SQL server and trying to write them to files in Azure storage account container. When running Sling it stores files locally in the folder with same name as connection name, instead of Azure storage account.

My config: 
 
```
connections:
  adls:
    type: azure
    account: my_storage_account
    container: my_container
    conn_str: DefaultEndpointsProtocol=https;AccountName=...
```
Files are saved to folder named `adls`
