### ISSUE TITLE
Dollar-Sign interpretation in replication

### ISSUE THREAD

**Issue by skostrewa** [slingdata-io/sling-cli#455]
## Issue Description

- Description of the issue: I updated sling today because the binary-date, of the dev-version i obtained in the past, expired. When i used the new version i observed, that the single dollar-sign in front of the ID now disappears. In recent versions it did not disappear and the name of the table was constructed as expected. now i need to use two dollar-signs to end up with one in the final object name. It seems like it gets consumed when replacing the variable, which makes little sense to me since the first variable is being replaced without any dollar-sign present.

- Sling version (`sling --version`): 1.3.1

- Operating System (`linux`, `mac`, `windows`): Windows 10

- Replication Configuration: 

```yaml
source: test1
target: test2

streams:
  dbo."{Mandant}$G_L Account${ID}": # adding two dollar-signs in front of the second variable works, it gets translated to dbo."test123$G_L Account$135c620c-6584-415c-b369-b93adcf5c94f"
    object: '"G_L Account"'

  dbo."{Mandant}$G_L Entry${ID}":
    object: '"G_L Entry"'

env:
  Mandant: "test123"
  ID: "135c620c-6584-415c-b369-b93adcf5c94f"
```

- Log Output (please run command with `-d`): 

```
11:04AM INF Sling Replication [2 streams] | test1 -> test2

11:04AM INF [1 / 2] running stream dbo."test123$G_L Account135c620c-6584-415c-b369-b93adcf5c94f"
11:04AM INF connecting to source database (azuresql)
11:04AM INF connecting to target database (postgres)
11:04AM INF reading from source database
11:04AM INF execution failed
did not find any columns for "dbo"."test123$G_L Account135c620c-6584-415c-b369-b93adcf5c94f". Perhaps it does not exists, or user does not have read permission.

11:04AM INF [2 / 2] running stream dbo."test123$G_L Entry135c620c-6584-415c-b369-b93adcf5c94f"
11:04AM INF connecting to source database (azuresql)
11:04AM INF connecting to target database (postgres)
11:04AM INF reading from source database
11:04AM INF execution failed
did not find any columns for "dbo"."test123$G_L Entry135c620c-6584-415c-b369-b93adcf5c94f". Perhaps it does not exists, or user does not have read permission.

11:04AM INF Sling Replication Completed in 1s | BusinessCentral -> DWH | 0 Successes | 2 Failures


fatal:
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--------------------------- dbo."test123$G_L Account135c620c-6584-415c-b369-b93adcf5c94f" ---------------------------
~ Could not get source columns
did not find any columns for "dbo"."test123$G_L Account135c620c-6584-415c-b369-b93adcf5c94f". Perhaps it does not exists, or user does not have read permission.

--------------------------- dbo."test123$G_L Entry135c620c-6584-415c-b369-b93adcf5c94f" ---------------------------
~ Could not get source columns
did not find any columns for "dbo"."test123$G_L Entry135c620c-6584-415c-b369-b93adcf5c94f". Perhaps it does not exists, or user does not have read permission.
```
