### ISSUE TITLE
BUG: Could not unload to stage files

### ISSUE THREAD

**Issue by miriamcastel** [slingdata-io/sling-cli#456]
## Issue Description

This is a continuation of the bug issue https://github.com/slingdata-io/sling-cli/issues/440#issuecomment-2507574247. After updating to version 1.2.23, the replication ran successfully for a few days. Then we got the same error: 
```
Stage 'RAW.PUBLIC.SLING_STAGING' does not exist or not authorized.
```
- Sling version (`sling --version`): 1.2.23

- Replication Configuration: 
```yaml
source: SOURCE_DB
target: TARGET_DB

defaults:
  mode: incremental
  object: "POSTGRES_DATABASE.METADATA_DB__{stream_table}"
  source_options:
    empty_as_null: false
  target_options:
    column_casing: snake

streams:
  metadata_db.account_id_key:
    primary_key: [proj_id]
    mode: full-refresh
  metadata_db.add_on_entitlement:
    primary_key: [id]
    mode: full-refresh
```

- Log Output (please run command with `-d`): 
```
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--------------------------- metadata_db.account_id_key ---------------------------
~ Could not unload to stage files
~ SQL Error for:
COPY INTO '@sling_staging/sling_temp/1732867547193/01_'
from (select * from "METADATA_DB"."ACCOUNT_ID_KEY")
FILE_FORMAT = (
TYPE = CSV
RECORD_DELIMITER = '\n'
NULL_IF = '\\N'
COMPRESSION = GZIP
ESCAPE_UNENCLOSED_FIELD = NONE
FIELD_OPTIONALLY_ENCLOSED_BY = '0x22'
)
HEADER = TRUE
002003 (02000): SQL compilation error:
Stage 'RAW.PUBLIC.SLING_STAGING' does not exist or not authorized.
```
