### ISSUE TITLE
JSON columns are mapped to an invalid type in Azure SQL (MSSQL).

### ISSUE THREAD

**Issue by ernestoalejo** [slingdata-io/sling-cli#470]
## Issue Description

- Description of the issue:

When a connection to an Azure SQL database is detected [here](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/database/database_sqlserver.go#L181), the JSON columns in the source data (originating from MySQL, though this detail is not relevant to the issue) are mapped to an invalid data type.

For a plain SQL Server, the mapping correctly uses `nvarchar(max)`. However, when Azure SQL is detected, it maps to `varchar(65535)` instead:

https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/templates/types_general_to_native.tsv?plain=1#L9

This data type is invalid, resulting in the following error for any table containing JSON columns:

```
mssql: The size (65535) given to the column 'options' exceeds the maximum allowed for any data type (8000).
```

Can this value be safely changed to the correct `nvarchar(max)`, or is there a specific reason for using the other one?

- Sling version (`sling --version`): 
Version: 1.3.3

- Operating System (`linux`, `mac`, `windows`): 
linux

- Replication Configuration: 

```yaml
source: MYSQL_URL
target: SQLSERVER_URL
defaults:
  mode: full-refresh

streams:
  'intranet.*':
    object: 'intranet.{stream_table}'
```
