### ISSUE TITLE
Unable to run Sling agent on AKS/hosted container service(s)

### ISSUE THREAD

**Issue by PhilBroderickCrezco** [slingdata-io/sling-cli#473]
## Issue Description

Following the docs to run a self-hosted agent in Docker (https://docs.slingdata.io/sling-platform/agents#running-a-self-hosted-agent), it works fine locally. However, when attempting to run it in AKS/Azure Container Instances/Azure Container Apps, it fails with the following error:

```
Error: Failed to start container sling, Error response: to create containerd task: failed to create shim task: failed to create container 89cb8c3728648db0dbd698d1b89bdafc04c2362ef330aa8f4be7206b08c13c30: guest RPC failure: failed to create container: failed to run runc create/exec call for container 89cb8c3728648db0dbd698d1b89bdafc04c2362ef330aa8f4be7206b08c13c30 with exit status 1: container_linux.go:380: starting container process caused: exec: "agent run": executable file not found in $PATH: unknown |  
```
- Description of the issue: Unable to run Sling agent on AKS/Azure Container services

- Sling version (`sling --version`): Latest docker image

- Operating System (`linux`, `mac`, `windows`): linux/windows

- Replication Configuration: 
Example K8s deployment:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sling-data-replication

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sling
  namespace: sling-data-replication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sling
  template:
    metadata:
      labels:
        app: sling
    spec:
      containers:
        - name: sling
          image: r.slingdata.io/sling
          env:
            - name: SLING_AGENT_KEY
              value: MY_AGENT_KEY
          command: ["agent run"]
```

**Comment by flarco** [comment]
Hey, can you try: 

```yaml
      containers:
      - name: sling-agent
        image: r.slingdata.io/sling
        command: ["sling"]  # Specify the command as an array
        args: ["agent", "run"]  # Specify the arguments as an array
        env:
        - name: SLING_AGENT_KEY
          value: MY_AGENT_KEY
```

**Comment by PhilBroderickCrezco** [comment]
Thanks @flarco, that looks to be a bit more successful. Still getting a termination of the container, but I think there's some other config bits I'm missing. Thanks for the prompt response!

**Comment by flarco** [comment]
Closing, assuming this worked, feel free to re-open

**Comment by PhilBroderickCrezco** [comment]
Hi @flarco, sorry was off for Christmas so only getting back to this now. I got past the previous error, but I'm now getting this:
```
INF sling agent (241227_1051)                                                                                                                                                             │
│ fatal:                                                                                                                                                                                            │
│ ~ could not start agent                                                                                                                                                                           │
│ could not lock cache. Do you have a sling agent already running?
```

Any ideas? I'm using Azure Files (via the [CSI driver](https://learn.microsoft.com/en-us/azure/aks/azure-files-csi)) to provide persistent volume for the agent, so possibly something to do with that?

**Comment by flarco** [comment]
🤔, interesting. Do you mind sharing your modified K8s deployment config?

**Comment by PhilBroderickCrezco** [comment]
Certainly, here you go:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sling-data-replication

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile
  namespace: sling-data-replication
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sling
  namespace: sling-data-replication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sling
  template:
    metadata:
      labels:
        app: sling
    spec:
      containers:
        - name: sling-agent
          image: r.slingdata.io/sling
          env:
            - name: SLING_AGENT_KEY
              value: MY_AGENT_KEY
          command: ["sling"]
          args: ["agent", "run"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /home/sling
              readOnly: false
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: pvc-azurefile
```

**Comment by flarco** [comment]
Ok, can you try a combination of these settings:
1. `ReadWriteOnce` instead of `ReadWriteMany`
2. Use `storageClassName: azurefile-csi-premium` instead of `storageClassName: azurefile-csi`
3. Can you try with `mountOptions`:
```yaml
spec:
  persistentVolumeClaim:
    claimName: pvc-azurefile
  mountOptions:
    - cache=strict
    - nolock
  ```

**Comment by flarco** [comment]
Also, can you clear out the volume first? The agent uses sqlite to persist some caching information, so a fresh volume may be needed to clear out the stale lock files. I think another solution may be to clear out the lock files on startup (by the agent itself), but let's see how the above suggestions work.

**Comment by PhilBroderickCrezco** [comment]
> Ok, can you try a combination of these settings:
> 
> 1. `ReadWriteOnce` instead of `ReadWriteMany`
> 2. Use `storageClassName: azurefile-csi-premium` instead of `storageClassName: azurefile-csi`
> 3. Can you try with `mountOptions`:
> 
> ```yaml
> spec:
>   persistentVolumeClaim:
>     claimName: pvc-azurefile
>   mountOptions:
>     - cache=strict
>     - nolock
> ```

None of these seemed to work 😞 

I tried the first 2 suggestions in isolation/combination, and got the same error. With the third suggestion, the syntax you provided didn't work. I needed to alter the deployment to set the `mountOptions` on the `StorageClass`, then reference that in the `PersistentVolumeClaim`. However, the mount failed due to invalid mount arguments 😕 I fiddled about with different options but haven't had any success. This is the current deployment configuration:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sling-data-replication

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-azurefile
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - cache=strict
  - nolock
parameters:
  skuName: Premium_LRS

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile
  namespace: sling-data-replication
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: sc-azurefile

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sling
  namespace: sling-data-replication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sling
  template:
    metadata:
      labels:
        app: sling
    spec:
      containers:
        - name: sling-agent
          image: r.slingdata.io/sling
          env:
            - name: SLING_AGENT_KEY
              value: MY_AGENT_KEY
          command: ["sling"]
          args: ["agent", "run"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /home/sling
              readOnly: false
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: pvc-azurefile
```

**Comment by flarco** [comment]
Ok, can you pull the image again and retry? There is now logic to use in-memory caching instead, which should work just fine.

**Comment by PhilBroderickCrezco** [comment]
It's alive! Thank you very much for your help @flarco 🙏

**Comment by PhilBroderickCrezco** [comment]
Hey @flarco, sorry for reopening this (feel free to redirect this to a new issue) but I'm experiencing issues running a replication job on the AKS hosted agent, related to permissions, with the following error:

```
could not submit job to agent: 
~ could not chmod 755 /home/sling/.sling/bin/cli/dev/latest/sling
chmod /home/sling/.sling/bin/cli/dev/latest/sling: operation not permitted
context canceled
```

I can see the Sling CLI has been successfully downloaded into the Azure file share, but the agent is having trouble accessing it 😕 these are all the logs I have from the agent pod:
```
| INF Sling Job "Dev Version Job (mssql_staging_to_dev.yaml)" | 32 streams | 1 threads | mssql_staging -> mssql_dev agent_id=agent_hv9f6gv3wd1l01sf project_id=proj_ht51uj3jbacb10zs 
│ INF downloading sling-cli (dev/latest) for linux/amd64
```

For reference, this is the current deployment setup for the Azure file mount:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile
  namespace: sling-data-replication
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sling
  namespace: sling-data-replication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sling
  template:
    metadata:
      labels:
        app: sling
    spec:
      containers:
        - name: sling-agent
          image: r.slingdata.io/sling
          env:
            - name: SLING_AGENT_KEY
              valueFrom:
                secretKeyRef:
                  key: SLING_AGENT_KEY
                  name: kvsecret
          command: ["sling"]
          args: ["agent", "run"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /home/sling
              readOnly: false
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: pvc-azurefile
```
