### ISSUE TITLE
Parquet to MySQL date error

### ISSUE THREAD

**Issue by simonprydden** [slingdata-io/sling-cli#475]
I have some parquet files created by DuckDB, but when loading them into MySQL the dates are all being changed to '1970,-01-01'

```
source: MINIO_BUCKET
target: MYSQL

defaults:
  mode: full-refresh
  object: '{stream_file_folder}.{stream_file_name}'
  source_options:
    format: parquet

streams:
```

```
Metadata:
<pyarrow._parquet.FileMetaData object at 0x7355197ca2f0>
  created_by: DuckDB version v1.1.3 (build 19864453f7)
  num_columns: 36
  num_rows: 4017
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 3797

Number of Rows: 4017
Number of Columns: 36
Schema:
<pyarrow._parquet.ParquetSchema object at 0x7355197970c0>
required group field_id=-1 duckdb_schema {
  optional int32 field_id=-1 date_day (Date);
  optional int32 field_id=-1 day_of_week (Int(bitWidth=32, isSigned=true));
  optional int32 field_id=-1 day_of_week_iso (Int(bitWidth=32, isSigned=true));
  optional binary field_id=-1 day_of_week_name (String);
  optional binary field_id=-1 day_of_week_name_short (String);
  optional int64 field_id=-1 day_of_month (Int(bitWidth=64, isSigned=true));
  optional int64 field_id=-1 day_of_year (Int(bitWidth=64, isSigned=true));
...
pyarrow.Table
date_day: date32[day]
----
date_day: [[2015-01-01,2015-01-02,2015-01-03,2015-01-04,2015-01-05,...,2025-12-26,2025-12-27,2025-12-28,2025-12-29,2025-12-30]]
````

**Comment by flarco** [comment]
Can you try with the dev build? 
There is now logic to use duckdb under the hood by default.
Download from here: https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds

**Comment by simonprydden** [comment]
For additional context:

This issue appeared during a mini-project where I was using dbt-duckdb. I utilized DuckDB's capability to write data directly to an object store. However, to make the data accessible for visualization in a dashboard tool, I copied it into MySQL, as Metabase integrates more easily with MySQL.

**Comment by flarco** [comment]
@simonprydden have you tried with the latest [dev build](https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds)? Is it giving the same behavior as the stable relase?

**Comment by simonprydden** [comment]
Dev version is throw the below error

```
10:43AM INF Sling Replication | MINIO_BUCKET -> MYSQL | s3://gold/core/dim_date/
10:43AM INF connecting to target database (mysql)
10:43AM INF reading from source file system (s3)
10:43AM INF downloading duckdb 1.1.1 for linux/amd64
10:43AM INF execution failed

~ datastream error
~ could not get columns
no columns found for: select * from read_parquet(['s3://gold/core/dim_date/dim_date.parquet'])

context canceled

context canceled

fatal:
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--------------------------- s3://gold/core/dim_date/ ---------------------------
~ dataflow error while waiting for ready state
~ datastream error
~ could not get columns
no columns found for: select * from read_parquet(['s3://gold/core/dim_date/dim_date.parquet'])
```

**Comment by simonprydden** [comment]
```
connections:
  MINIO_BUCKET:
    type: s3
    access_key_id: redacted
    bucket: gold
    endpoint: http://localhost:9000
    secret_access_key: redacted
  
  MYSQL:
    type: mysql
    database: sling
    host: localhost
    password: redacted
    port: "3306"
    user: redacted

variables: {}
```

**Comment by flarco** [comment]
pushed some changes, can you download it once more, and try again? I think the `endpoint` value was not formatted correctly.

**Comment by flarco** [comment]
And if that doesn't work, can you glance over the logic [here](https://github.com/slingdata-io/sling-cli/blob/v1.3.5/core/dbio/iop/duckdb.go#L126-L154), and spot the issue? Since you have it working in duckdb yourself, what secret key is missing?

**Comment by simonprydden** [comment]
@flarco 

Still getting error, but have better error message now. :+1: 

```
IO Error: SSL connection failed error for HTTP HEAD to 'https://gold.localhost:9000/core/dim_date/dim_date.parquet'
```

For duckdb & Minio in the [docs](https://duckdb.org/docs/extensions/httpfs/s3api.html#overview-of-s3-secret-parameters), if you running locally, you need to change `USE_SSL=false` which should will fix HTTPS issue at the front.  Then it looks like it putting the bucket before the host name, it should look like this `http://localhost:9000/gold/core/dim_date/dim_date.parquet`

**Comment by flarco** [comment]
OK, I push more changes. You can change back your endpoint with the `http` scheme and remove `use_ssl`, sling will auto-set `USE_SSL=false` for the duckdb query.
Can you re-download and try again?

**Comment by simonprydden** [comment]
The latest version has fixed the http(s) issue, just need the bucket name to be in the correct location.

This path `s3://gold/core/dim_date/` is changing to `http://gold.localhost:9000/core/dim_date/dim_date.parquet`
it should be `http://loccalhost:9000/gold/core/dim_date/dim_date.parquet`

**Comment by flarco** [comment]
Ah ok, can you add `url_style: path` in your MINIO_BUCKET connection?

```yaml
connections:
  MINIO_BUCKET:
    type: s3
    access_key_id: redacted
    bucket: gold
    endpoint: http://localhost:9000
    secret_access_key: redacted
    url_style: path
```
