### ISSUE TITLE
Writing to BigQuery fails with "Exceeded rate limits" in 1.3

### ISSUE THREAD

**Issue by nordictiger** [slingdata-io/sling-cli#485]
## Issue Description

- Description of the issue: 
Starting from 1.3 moving data from PostgreSQL to BigQuery started to fail with message {Location: "table.write"; Message: "Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas"; Reason: "rateLimitExceeded"}

It happens only in few specific tables, I suspect that common feature for these tables are (large) JSON type field. 

While message refers to hitting the rate limits on BigQuery, the tables are relative small (few tens of thousands of records) and version 1.2 has been writing the same tables without issues.

- Sling version (`sling --version`): Sling version: 1.3.5 (linux amd64)

- Operating System (`linux`, `mac`, `windows`):  linux (in Docker)

- Replication Configuration: 

```yaml
    source: prod_pg_ai
    target: prod_bq

    # default config options which apply to all streams
    defaults:
      mode: full-refresh
      object: ex_prod_pg.ai_{stream_schema}_{stream_table}

    streams:
      public.tasks:

    env:
      SLING_LOADED_AT_COLUMN: true 
      SLING_ALLOW_EMPTY: true
      SLING_LOGGING: JSON```

- Log Output (please run command with `-d`): 

```
~ Error copying from gs://theydo-sling-staging-eu/sling_temp/`ex_prod_pg`.`ai_public_tasks_tmp`.csv/part.01.0016.csv into `ex_prod_pg`.`ai_public_tasks_tmp`
--- database_bigquery.go:708 func3 ---
~ Error in Import Task
--- database_bigquery.go:825 CopyFromGCS ---
{Location: "table.write"; Message: "Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas"; Reason: "rateLimitExceeded"}
context canceled
```
