### ISSUE TITLE
Use account and container values from connection config instead of full URL

### ISSUE THREAD

**Issue by nixent** [slingdata-io/sling-cli#51]
Configuration for Azure storage account require `account` and `container` to be specified

```
connections:
  AZURE_STORAGE:
    type: azure
    account: <account>
    container: <container>
    sas_svc_url: '<sas_svc_url>'
```

In same time source `stream` and target `object` require full `URL` which also includes `account` and `container`:
```
source:
  conn: MY_AZURE_CONT
  stream: https://my_account.blob.core.windows.net/my-container/my_file.csv
```

Would it make sense to use config from MY_AZURE_CONT and have stream/object starting from container as root?

```
source:
  conn: MY_AZURE_CONT
  stream: my-path/my-subpath/my_file.csv
```
