### ISSUE TITLE
Can't find column for table key in Postgres when doing snake case column transformation

### ISSUE THREAD

**Issue by somiandras** [slingdata-io/sling-cli#532]
## Issue Description

I'm replicating data from a MySQL db where column names are mostly camelCase with a couple of snake case names (I have no control over this). I have `column_casing: snake` set in target options. I want to also set indexes on the replicated data, but that only works with column names like `id` and `update_dt`, but it errors out on camel case ones. I'm getting this (I'm running the replication in Dagster):

```
~ could not set keys for "raw"."share_class_tmp"
could not set index key. Did not find column company_id [0m
Sling command failed
```

I tried all the variations, camel case, snake case and all lowercaps, just in case, all leads to this error. (I guess it should work with the transformed column name, that's what I'll have in the replicated table after all.) The example below works fine (or at least doesn't fail in any obvious ways) if I only keep `update_dt` in the index.

- Sling version (`sling --version`): sling==1.4.4

- Operating System (`linux`, `mac`, `windows`): linux in docker

- Replication Configuration: 

```yaml
source: MAIN_DB
target: WAREHOUSE_URL

defaults:
  object: raw.{stream_table}

  target_options:
    column_casing: snake
  ...
  "{mysql_db_name}.share_classes":
    object: raw.share_class
    mode: incremental
    primary_key: [id]
    update_key: update_dt
    select:
      - id
      - create_dt
      - update_dt
      - companyId
      - ...
    target_options:
      delete_missing: hard
      table_keys:
        primary: [id]
        index: [update_dt, company_id]
```

- Log Output (please run command with `-d`): 

```
[90m8:10AM[0m [32mINF[0m connecting to source database (mysql)
[90m8:10AM[0m [32mINF[0m connecting to target database (postgres)
[90m8:10AM[0m [32mINF[0m getting checkpoint value
[90m8:10AM[0m [32mINF[0m reading from source database
[90m8:10AM[0m [32mINF[0m [31mexecution failed[0m

[31mfatal:
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--------------------------- collective_main_staging.share_classes ---------------------------
~ Could not set column keys
could not set index key. Did not find column company_id[0m
Sling command failed```
