### ISSUE TITLE
Add support for custom SQL flexibility in backfill mode

### ISSUE THREAD

**Issue by royandhika** [slingdata-io/sling-cli#537]
Based on the Sling documentation and GitHub discussions, I couldn't find a way to perform backfill replication using customSQL mode with the same flexibility as the `{incremental_value}` placeholder in incremental mode.
Source: [slingdocs](https://docs.slingdata.io/concepts/replication/modes#incremental-or-backfill-mode-with-custom-sql)

From what I’ve seen, backfill mode only supports `{incremental_where_cond}`, which is automatically constructed as:
```sql
WHERE {update_key} >= {start_value} AND {update_key} <= {end_value}
``` 
Source: [#41](https://github.com/slingdata-io/sling-cli/issues/41#issuecomment-1866364077)

Based on that statement, I tried to write the condition manually inside the custom SQL query like this:
```yaml
defaults:
  object: '{ENV_SCHEMA}_dl.raw_{stream_table}'
  mode: backfill
  primary_key: [id]
  update_key: created_time
  source_options:
    range: '2024-11-10, 2024-11-11'

env:
  SLING_LOADED_AT_COLUMN: timestamp

streams:
  schema.table:
    update_key: modified_time
    sql: |
      SELECT
        *
        ,COALESCE(last_info_time, created_time) AS modified_time
      FROM {stream_schema}.{stream_table}
      WHERE COALESCE(last_info_time, created_time) >= {start_value}
        AND COALESCE(last_info_time, created_time) <= {end_value}
      ORDER BY COALESCE(last_info_time, created_time)
```

But this didn’t work as expected.

Would it be possible to support this as a new feature? I believe it would be helpful to have more flexibility when using backfill mode, especially when dealing with multiple `{update_key}` values inside custom SQL.

Thanks! #215 #41
