### ISSUE TITLE
mssql to sqlite, the ID become id

### ISSUE THREAD

**Issue by wenerme** [slingdata-io/sling-cli#538]
## Issue Description

- Description of the issue: 

```yaml
source: MSSQL
target: DUMP

defaults:
  mode: full-refresh
  object: "{stream_table}"
  primary_key: [ID]

streams:
  dbo.*:
```

the source table is `ID`, but the sqlite became `id`

```
.schema T_Users
CREATE TABLE IF NOT EXISTS "T_Users" ("id" integer,
"UserID" integer,
```

- Sling version (`sling --version`): 

Version: 1.4.4

- Operating System (`linux`, `mac`, `windows`): 

macos

- Replication Configuration: 

- Log Output (please run command with `-d`): 

i thinks this dose not matter
