### ISSUE TITLE
Snowflake datasource with target_option.column_casing=source is broken on COPY INTO statement

### ISSUE THREAD

**Issue by IamShobe** [slingdata-io/sling-cli#547]
## Issue Description

- Description of the issue: 
Hi there :), first of all must say - awesome work! This tool is very useful - so keep up with the good work 💪 and I appreciate the generous free plan.

I've been testing the CLI tool with the replication of Snowflake tables from different sources.
The thing is that I have non-standardized tables in my Snowflake - where the column names are lower case instead of upper case.

For example:
```
create table "Entity" ("id" varchar(256),
"customer_id" varchar(256),
"name" varchar(256))
```

So starting from version v1.4.5 - we need to explicitly use `target_option.column_casing=source` - if I want to preserve the same casing.

But then sling fails on the COPY INTO from stage statement:
(from debug logs)
```
COPY INTO "NEW_SCHEMA"."PUBLIC_ENTITY_TMP" ("ID", "CUSTOMER_ID", "NAME")
from (
  select T.$1, T.$2, T.$3
  from @"NEW_SCHEMA"."SLING_STAGING"/new_schema.public_entity_tmp/2025-04-24T161722.337 as T
)
```

Looks like that the transient table is created correctly:
(from debug logs)
```
create transient table "NEW_SCHEMA"."PUBLIC_ENTITY_TMP" ("id" varchar(256),
"customer_id" varchar(256),
"name" varchar(256))
```
with good casing.

When forking the code looks like there's a redundant processing of the column names at:
core/dbio/database/database_snowflake.go:861
Commenting it out fixed the issue 🤔 
But not sure if there are other repercussions for this commenting out.

- Sling version (`sling --version`): v1.4.5

- Operating System (`linux`, `mac`, `windows`): mac

- Replication Configuration: 

```yaml
source: TEST1
target: TEST2

defaults:
  object: new_schema.{stream_schema}_{stream_table}
  target_options:
    column_casing: source

streams:
  public.entity:
    sql: |
      select * from public.entity 
      where 1 = 1
      and "customer_id" = '00000000-0000-0000-0000-000000000000' 
```
