### ISSUE TITLE
Mysql decimal(38,18) to Bigquery

### ISSUE THREAD

**Issue by nw-bongheelee** [slingdata-io/sling-cli#55]
hello. I have a question about column type.

The source is Mysql and the column type is decimal(38,18).
The target is Bigquery and when I synchronize, the source data is truncated as it is stored as NUMERIC.

ex: 2418474.103366277600000000 to 2418474.103366277

So I added table_ddl in yaml like below.

```
streams:
  test.historical:
    target_options:
      table_ddl: |
        CREATE TABLE IF NOT EXISTS `test_project.test.sling_historical`
        (
          id INT64,
          name STRING,
          test BIGNUMERIC
        )        
        ;
```

The table_ddl has created a BIGNUMERIC column in bigquery, but the data is still truncated like NUMERIC.

Is there any workaround?

Additionally, is it possible to use custom SQL in the replication like below?
```
streams:
  | 
  select id from test_table where id > 10;
  object: 'test.test_table'
```

Thanks.

**Comment by flarco** [comment]
Hey there. 

After a little bit of testing, your best bet is to send it over as a string, and then convert it inside of BigQuery with `PARSE_BIGNUMERIC` (with `target_options.post_sql`).

> Additionally, is it possible to use custom SQL in the replication like below?

Yes, like this (was missing in docs, just [added](https://docs.slingdata.io/sling-cli/replication)):

```yaml
streams:
  test.historical:
    sql: |
      select cast(col_decimal as char(30)) as col_decimal 
      from mysql.table1
    object: 'test.test_table_prep'
    target_options:
      post_sql: |
        create table test.test_table as 
        select PARSE_BIGNUMERIC(col_decimal) as col_decimal
        from test.test_table_prep;

        drop table test.test_table_prep;
```
