### ISSUE TITLE
Snowflake: Sing requires undocumented property `private_key_path` when using `snowflake_jwt`

### ISSUE THREAD

**Issue by GeoffTearle** [slingdata-io/sling-cli#552]
## Issue Description

- Description of the issue: 
When attempting to connect to snowflake using the `snowflake_jwt` authenticator, sling returns an error requiring that the property `private_key_path` must be set.

Unfortunately this isn't documented in the [sling connection docs](https://docs.slingdata.io/connections/database-connections/snowflake#setup), and I would really prefer to use `private_key` with the keys body instead.

- Sling version (`sling --version`): 

```
❯ sling --version
Version: 1.4.6
```

- Operating System (`linux`, `mac`, `windows`): 
mac
- Replication Configuration: 

```yaml
# Environment Credentials for Sling CLI
# See https://docs.slingdata.io/sling-cli/environment

# Holds all connection credentials for Extraction and Loading
connections:
  snowflake:
    type: 'snowflake'
    account: "some-account"
    user: "snowflake-user"
    authenticator: "SNOWFLAKE_JWT"
    database: "database"
    private_key: "path/to/key"
# Global variables for specific settings, available to all connections at runtime
variables:


```

- Log Output (please run command with `-d`): 

```
❯ sling conns test snowflake -d
fatal:
--- proc.go:272 main ---
--- sling_cli.go:507 main ---
--- sling_cli.go:543 cliInit ---
--- cli.go:286 CliProcess ---
--- sling_conns.go:194 processConns ---
--- connection_local.go:65 Test ---
--- connection_discover.go:24 Test ---
--- connection.go:275 AsDatabase ---
--- connection.go:292 AsDatabaseContext ---
~ could not test snowflake
--- database.go:327 NewConnContext ---
~ could not initiate snowflake
--- database_snowflake.go:52 Init ---
did not provide property `private_key_path` with authenticator=snowflake_jwt. See https://docs.slingdata.io/connections/database-connections/snowflake
```
