### ISSUE TITLE
GCP Pubsub support

### ISSUE THREAD

**Issue by edkry** [slingdata-io/sling-cli#556]
Are there plans to add GCP Pubsub support? 

I have a use case where I want to read from database and load it to a message queue. 

The idea is to load ids from database and then using separate application make API calls for each extracted id. Message queue would help in this case.

**Comment by flarco** [comment]
hey @edkry no plans to support GCP Pubsub, but if you want to make API calls for each record, you could use a [pipeline](https://docs.slingdata.io/concepts/pipeline).

Something like this:
```yaml
steps:

  - type: query
    connection: MY_DB
    query: select * from my_table limit 100
    id: data

  - type: group
    loop: state.data.result
    steps:
      - type: http
        url: "https://api.example.com/webhook"
        method: POST
        headers:
          Authorization: Bearer xxxxxxxxxxx
          Content-Type: application/json
        payload: '{"record": {loop_value}}'
```

Sling is about to get API reads, but it's not finished yet. API writes could come later on if it makes sense. Closing, feel free to comment.

**Comment by flarco** [comment]
Actually, not storage. Right now, only write to DBs with the `query` step.
That's a good suggestion. I think this could be added to the [`copy`](https://docs.slingdata.io/concepts/hooks/copy) step, with a new key called `body` (which sling could use instead of `from`).

```yaml
steps:

  - type: query
    connection: MY_DB
    query: select * from my_table limit 100
    id: data

  - type: group
    loop: state.data.result
    steps:
      - type: http
        id: hook
        url: "https://api.example.com/webhook"
        method: POST
        headers:
          Authorization: Bearer {env.token}
          Content-Type: application/json
        payload: '{"record": {loop_value}}'

      # writing to db
      - type: query
        connection: MY_DB
        query: insert into my_table values ( '{state.hook.response.json.value}' )
  
      # writing to file 
      - type: copy
        body: '{state.hook.response.text}' # ( body key not yet implemented )
        to: "gcs/data-lake/raw/file_name.json"
        on_failure: abort

env:
  token: ${API_TOKEN}
```
