### ISSUE TITLE
SFTP Password Authentication?

### ISSUE THREAD

**Issue by FRSR** [slingdata-io/sling-cli#56]
When attempting to connect to a SFTP site using only username and password.   I get this error now:

"ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain"

my env.yaml looks like this:

```
connections:

  MY_SFTP:
    type: sftp
    host: <host>
    user: <user>
    port: <port>
    password: <password>
```
