### ISSUE TITLE
Post-hooks run in a transaction and can't create concurrent indices now

### ISSUE THREAD

**Issue by avegancafe** [slingdata-io/sling-cli#577]
## Issue Description

- Description of the issue: 

I was using post-hooks to regenerate indices concurrently before, and now with 1.4.10, it seems as if the post hooks are run in a transaction and you can't concurrently create indices in a transaction.
```
pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
```

- Sling version (`sling --version`): 1.4.10

- Operating System (`linux`, `mac`, `windows`): ubuntu

- Replication Configuration: 

```yaml
source: GOOGLE_STORAGE
target: POSTGRES

defaults:
  mode: incremental
  source_options:
    format: parquet

env:
  SLING_THREADS: 8

streams:
  "provider_location/":
    object: public.web_app_providerlocation
    mode: full-refresh
    hooks:
      post:
        - type: query
          connection: POSTGRES
          query: |
            create index concurrently if not exists providerlocation_id on web_app_providerlocation (id);
            create index concurrently if not exists providerlocation_provider_id_state on web_app_providerlocation (provider_id, state);
            create index concurrently if not exists providerlocation_state on web_app_providerlocation (state);
            create index concurrently if not exists providerlocation_county_fips on web_app_providerlocation (county_fips);

            create index concurrently if not exists providerlocation_medical_group on web_app_providerlocation (medical_group);
            create index concurrently if not exists providerlocation_medical_group_state on web_app_providerlocation (medical_group, state);
            create index concurrently if not exists providerlocation_medical_group_state_county_fips on web_app_providerlocation (medical_group, state, county_fips);
            create index concurrently if not exists providerlocation_beds on web_app_providerlocation (beds);
            analyze web_app_providerlocation

  "provider/":
    object: public.web_app_provider
    primary_key: id

  "carrier/":
    object: public.web_app_carrier
    primary_key: id

  "plan/":
    object: public.web_app_plan
    primary_key: id
    mode: full-refresh
    hooks:
      post:
        - type: query
          connection: POSTGRES
          query: |
            create index concurrently if not exists plan_id_idx on web_app_plan (id);
            create index concurrently if not exists plan_carrier_idx on web_app_plan (carrier_id);
            analyze web_app_plan

  "provider_plan/":
    object: public.web_app_providerplan
    primary_key: id
    mode: full-refresh
    hooks:
      post:
        - type: query
          connection: POSTGRES
          query: |
            create index concurrently if not exists providerplan_id on web_app_providerplan (id);
            create index concurrently if not exists providerplan_plan_id on web_app_providerplan (plan_id);
            create index concurrently if not exists providerplan_plan_id_provider_id on web_app_providerplan (plan_id, provider_id);
            create index concurrently if not exists providerplan_provider_idx on web_app_providerplan (provider_id);
            analyze web_app_providerplan

  "plan_service_area/":
    object: public.web_app_planservicearea
    mode: full-refresh
    hooks:
      post:
        - type: query
          connection: POSTGRES
          query: |
            create index concurrently if not exists planservicearea_plan_id_state on web_app_planservicearea (plan_id, state);
            analyze web_app_planservicearea

  "provider_ccn/":
    object: public.web_app_providerccn
    mode: full-refresh
    hooks:
      post:
        - type: query
          connection: POSTGRES
          query: |
            create index concurrently if not exists providerccn_provider_idx on web_app_providerccn (provider_id);
            analyze web_app_providerccn

  "provider_ipa_group/":
    object: public.web_app_provideripagroup
    mode: full-refresh
    hooks:
      post:
        - type: query
          connection: POSTGRES
          query: |
            create index concurrently if not exists provideripagroup_provider_idx  on web_app_provideripagroup (provider_id);
            create index concurrently if not exists provideripagroup_ipa_group_idx on web_app_provideripagroup (ipa_group);

  "provider_npi/":
    object: public.web_app_providernpi
    mode: full-refresh
    hooks:
      post:
        - type: query
          connection: POSTGRES
          query: |
            create index concurrently if not exists providernpi_provider_idx on web_app_providernpi (provider_id);
            analyze web_app_providernpi;

  "provider_claim_count/":
    object: public.web_app_providerclaimcount
    mode: full-refresh
    hooks:
      post:
        - type: query
          connection: POSTGRES
          query: |
            create index concurrently if not exists pcc_category_idx on web_app_providerclaimcount (category_name);
            create index concurrently if not exists pcc_provider_state_category_idx on web_app_providerclaimcount (provider_id, state, category_name);
            create index concurrently if not exists pcc_provider_state_county_idx on web_app_providerclaimcount (provider_id, state, county_fips);
            create index concurrently if not exists pcc_provider_state_idx on web_app_providerclaimcount (provider_id, state);
            create index concurrently if not exists pcc_provider_idx on web_app_providerclaimcount (provider_id);
            analyze web_app_providerclaimcount;

  "specialty/":
    object: public.web_app_specialty
    mode: incremental
    primary_key: id

  "provider_specialty/":
    object: public.web_app_providerspecialty
    mode: full-refresh
    hooks:
      post:
        - type: query
          connection: POSTGRES
          query: |
            create index concurrently if not exists providerspecialty_pr_spec_idx on web_app_providerspecialty (provider_id, specialty_id);

```

- Log Output (please run command with `-d`): 

```
1:27PM INF Sling CLI | https://slingdata.io/
1:27PM INF Sling Replication "replication.yml" | 12 streams | 8 threads | GOOGLE_STORAGE -> POSTGRES exec_id=2yalALDG36K0uVgU4GUqV7z6XvY
plan_service_area/    | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | plan_service_area/
provider_ipa_group/   | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | provider_ipa_group/
provider_location/    | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | provider_location/
carrier/              | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | carrier/
provider_location/    | 1:27PM INF connecting to target database (postgres)
provider_ipa_group/   | 1:27PM INF connecting to target database (postgres)
provider/             | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | provider/
plan_service_area/    | 1:27PM INF connecting to target database (postgres)
carrier/              | 1:27PM INF connecting to target database (postgres)
plan/                 | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | plan/
provider_plan/        | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | provider_plan/
provider/             | 1:27PM INF connecting to target database (postgres)
provider_ccn/         | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | provider_ccn/
plan/                 | 1:27PM INF connecting to target database (postgres)
provider_plan/        | 1:27PM INF connecting to target database (postgres)
provider_ccn/         | 1:27PM INF connecting to target database (postgres)
provider/             | 1:27PM INF reading from source file system (gs)
provider_plan/        | 1:27PM INF reading from source file system (gs)
provider_location/    | 1:27PM INF reading from source file system (gs)
provider_ipa_group/   | 1:27PM INF reading from source file system (gs)
carrier/              | 1:27PM INF reading from source file system (gs)
plan_service_area/    | 1:27PM INF reading from source file system (gs)
provider_ccn/         | 1:27PM INF reading from source file system (gs)
plan/                 | 1:27PM INF reading from source file system (gs)
provider_ccn/         | 1:27PM INF writing to target database [mode: full-refresh]
carrier/              | 1:27PM INF writing to target database [mode: incremental]
plan_service_area/    | 1:27PM INF writing to target database [mode: full-refresh]
provider_ccn/         | 1:27PM INF created table "public"."web_app_providerccn_tmp"
provider_ccn/         | 1:27PM INF streaming data
carrier/              | 1:27PM INF created table "public"."web_app_carrier_tmp"
carrier/              | 1:27PM INF streaming data
provider_ipa_group/   | 1:27PM INF writing to target database [mode: full-refresh]
plan_service_area/    | 1:27PM INF created table "public"."web_app_planservicearea_tmp"
plan_service_area/    | 1:27PM INF streaming data
provider/             | 1:27PM INF writing to target database [mode: incremental]
provider_ipa_group/   | 1:27PM INF created table "public"."web_app_provideripagroup_tmp"
provider_ipa_group/   | 1:27PM INF streaming data
provider/             | 1:27PM INF created table "public"."web_app_provider_tmp"
provider/             | 1:27PM INF streaming data
provider_ccn/         | 1:27PM INF created table "public"."web_app_providerccn"
carrier/              | 1:27PM INF inserted 185 rows into "public"."web_app_carrier" in 2 secs [83 r/s]
carrier/              | 1:27PM INF execution succeeded
plan/                 | 1:27PM INF writing to target database [mode: full-refresh]
provider_ccn/         | 1:27PM INF inserted 22205 rows into "public"."web_app_providerccn" in 2 secs [9,182 r/s]
provider_ccn/         | 1:27PM INF execution succeeded
plan/                 | 1:27PM INF created table "public"."web_app_plan_tmp"
carrier/              | 
plan/                 | 1:27PM INF streaming data
provider_ccn/         | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_ccn/         | 
provider_ccn/         | fatal:
provider_ccn/         | ~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
provider_ccn/         | --------------------------- provider_ccn/ ---------------------------
provider_ccn/         | ~ Error executing [tx: false] create index concurrently if not exists providerccn_provider_idx on web_app_providerccn (provider_id);
provider_ccn/         | analyze web_app_providerccn
provider_ccn/         | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_npi/         | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | provider_npi/
provider_npi/         | 1:27PM INF connecting to target database (postgres)
plan/                 | 1:27PM INF created table "public"."web_app_plan"
provider_claim_count/ | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | provider_claim_count/
provider_claim_count/ | 1:27PM INF connecting to target database (postgres)
plan/                 | 1:27PM INF inserted 3703 rows into "public"."web_app_plan" in 3 secs [1,075 r/s]
provider_npi/         | 1:27PM INF reading from source file system (gs)
plan/                 | 1:27PM INF execution succeeded
provider_claim_count/ | 1:27PM INF reading from source file system (gs)
plan/                 | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
plan/                 | 
plan/                 | fatal:
plan/                 | ~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
plan/                 | --------------------------- plan/ ---------------------------
plan/                 | ~ Error executing [tx: false] create index concurrently if not exists plan_id_idx on web_app_plan (id);
plan/                 | create index concurrently if not exists plan_carrier_idx on web_app_plan (carrier_id);
plan/                 | analyze web_app_plan
plan/                 | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
specialty/            | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | specialty/
specialty/            | 1:27PM INF connecting to target database (postgres)
specialty/            | 1:27PM INF reading from source file system (gs)
specialty/            | 1:27PM INF writing to target database [mode: incremental]
specialty/            | 1:27PM INF created table "public"."web_app_specialty_tmp"
specialty/            | 1:27PM INF streaming data
provider_npi/         | 1:27PM INF writing to target database [mode: full-refresh]
provider_npi/         | 1:27PM INF created table "public"."web_app_providernpi_tmp"
provider_npi/         | 1:27PM INF streaming data
specialty/            | 1:27PM INF inserted 358 rows into "public"."web_app_specialty" in 1 secs [225 r/s]
specialty/            | 1:27PM INF execution succeeded
specialty/            | 
provider_location/    | 1:27PM INF writing to target database [mode: full-refresh]
provider_ipa_group/   | 1:27PM INF created table "public"."web_app_provideripagroup"
provider_location/    | 1:27PM INF created table "public"."web_app_providerlocation_tmp"
plan_service_area/    | 1:27PM INF created table "public"."web_app_planservicearea"
provider_location/    | 1:27PM INF streaming data
provider_specialty/   | 1:27PM INF Sling Replication | GOOGLE_STORAGE -> POSTGRES | provider_specialty/
provider_specialty/   | 1:27PM INF connecting to target database (postgres)
provider_specialty/   | 1:27PM INF reading from source file system (gs)
plan_service_area/    | 1:27PM INF inserted 367572 rows into "public"."web_app_planservicearea" in 7 secs [50,562 r/s]
provider_ipa_group/   | 1:27PM INF inserted 408722 rows into "public"."web_app_provideripagroup" in 7 secs [56,052 r/s]
plan_service_area/    | 1:27PM INF execution succeeded
provider_ipa_group/   | 1:27PM INF execution succeeded
plan_service_area/    | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_ipa_group/   | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
plan_service_area/    | 
plan_service_area/    | fatal:
plan_service_area/    | ~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
plan_service_area/    | --------------------------- plan_service_area/ ---------------------------
plan_service_area/    | ~ Error executing [tx: false] create index concurrently if not exists planservicearea_plan_id_state on web_app_planservicearea (plan_id, state);
plan_service_area/    | analyze web_app_planservicearea
plan_service_area/    | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_ipa_group/   | 
provider_ipa_group/   | fatal:
provider_ipa_group/   | ~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
provider_ipa_group/   | --------------------------- provider_ipa_group/ ---------------------------
provider_ipa_group/   | ~ Error executing [tx: false] create index concurrently if not exists provideripagroup_provider_idx  on web_app_provideripagroup (provider_id);
provider_ipa_group/   | create index concurrently if not exists provideripagroup_ipa_group_idx on web_app_provideripagroup (ipa_group);
provider_ipa_group/   | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_specialty/   | 1:27PM INF writing to target database [mode: full-refresh]
provider_specialty/   | 1:27PM INF created table "public"."web_app_providerspecialty_tmp"
provider_specialty/   | 1:27PM INF streaming data
provider_claim_count/ | 1:27PM INF writing to target database [mode: full-refresh]
provider_claim_count/ | 1:27PM INF created table "public"."web_app_providerclaimcount_tmp"
provider_claim_count/ | 1:27PM INF streaming data
provider_plan/        | 1:27PM INF writing to target database [mode: full-refresh]
provider_plan/        | 1:27PM INF created table "public"."web_app_providerplan_tmp"
provider_plan/        | 1:27PM INF streaming data
provider_npi/         | 1:27PM INF created table "public"."web_app_providernpi"
provider_specialty/   | 1:27PM INF created table "public"."web_app_providerspecialty"
provider_npi/         | 1:28PM INF inserted 4035635 rows into "public"."web_app_providernpi" in 57 secs [69,698 r/s]
provider_npi/         | 1:28PM INF execution succeeded
provider_npi/         | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_npi/         | 
provider_npi/         | 
provider_npi/         | fatal:
provider_npi/         | ~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
provider_npi/         | --------------------------- provider_npi/ ---------------------------
provider_npi/         | ~ Error executing [tx: false] create index concurrently if not exists providernpi_provider_idx on web_app_providernpi (provider_id);
provider_npi/         | analyze web_app_providernpi;
provider_npi/         | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_specialty/   | 1:28PM INF inserted 4407625 rows into "public"."web_app_providerspecialty" in 58 secs [75,257 r/s]
provider_specialty/   | 1:28PM INF execution succeeded
provider_location/    | 1:28PM INF created table "public"."web_app_providerlocation"
provider_location/    | 1:28PM INF inserted 5764780 rows into "public"."web_app_providerlocation" in 103 secs [55,869 r/s]
provider_location/    | 1:28PM INF execution succeeded
provider_location/    | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_location/    | 
provider_location/    | fatal:
provider_location/    | ~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
provider_location/    | --------------------------- provider_location/ ---------------------------
provider_location/    | ~ Error executing [tx: false] create index concurrently if not exists providerlocation_id on web_app_providerlocation (id);
provider_location/    | create index concurrently if not exists providerlocation_provider_id_state on web_app_providerlocation (provider_id, state);
provider_location/    | create index concurrently if not exists providerlocation_state on web_app_providerlocation (state);
provider_location/    | create index concurrently if not exists providerlocation_county_fips on web_app_providerlocation (county_fips);
provider_location/    | 
provider_location/    | create index concurrently if not exists providerlocation_medical_group on web_app_providerlocation (medical_group);
provider_location/    | create index concurrently if not exists providerlocation_medical_group_state on web_app_providerlocation (medical_group, state);
provider_location/    | create index concurrently if not exists providerlocation_medical_group_state_county_fips on web_app_providerlocation (medical_group, state, county_fips);
provider_location/    | create index concurrently if not exists providerlocation_beds on web_app_providerlocation (beds);
provider_location/    | analyze web_app_providerlocation
provider_location/    | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider/             | 1:29PM INF inserted 3863539 rows into "public"."web_app_provider" in 138 secs [27,844 r/s]
provider/             | 1:29PM INF execution succeeded
provider/             | 
provider_claim_count/ | 1:38PM INF created table "public"."web_app_providerclaimcount"
provider_claim_count/ | 1:40PM INF inserted 57969694 rows into "public"."web_app_providerclaimcount" in 784 secs [73,911 r/s]
provider_claim_count/ | 1:40PM INF execution succeeded
provider_claim_count/ | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_claim_count/ | 
provider_claim_count/ | 
provider_claim_count/ | fatal:
provider_claim_count/ | ~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
provider_claim_count/ | --------------------------- provider_claim_count/ ---------------------------
provider_claim_count/ | ~ Error executing [tx: false] create index concurrently if not exists pcc_category_idx on web_app_providerclaimcount (category_name);
provider_claim_count/ | create index concurrently if not exists pcc_provider_state_category_idx on web_app_providerclaimcount (provider_id, state, category_name);
provider_claim_count/ | create index concurrently if not exists pcc_provider_state_county_idx on web_app_providerclaimcount (provider_id, state, county_fips);
provider_claim_count/ | create index concurrently if not exists pcc_provider_state_idx on web_app_providerclaimcount (provider_id, state);
provider_claim_count/ | create index concurrently if not exists pcc_provider_idx on web_app_providerclaimcount (provider_id);
provider_claim_count/ | analyze web_app_providerclaimcount;
provider_claim_count/ | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_specialty/   | 
provider_plan/        | 2:06PM INF created table "public"."web_app_providerplan"
provider_plan/        | 2:13PM INF inserted 362329450 rows into "public"."web_app_providerplan" in 2776 secs [[130](https://github.com/j2-health/data/actions/runs/15681863490/job/44175399749#step:6:131),506 r/s]
provider_plan/        | 2:13PM INF execution succeeded
provider_plan/        | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
provider_plan/        | 
provider_plan/        | fatal:
provider_plan/        | ~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
provider_plan/        | --------------------------- provider_plan/ ---------------------------
provider_plan/        | ~ Error executing [tx: false] create index concurrently if not exists providerplan_id on web_app_providerplan (id);
provider_plan/        | create index concurrently if not exists providerplan_plan_id on web_app_providerplan (plan_id);
provider_plan/        | create index concurrently if not exists providerplan_plan_id_provider_id on web_app_providerplan (plan_id, provider_id);
provider_plan/        | create index concurrently if not exists providerplan_provider_idx on web_app_providerplan (provider_id);
provider_plan/        | analyze web_app_providerplan
provider_plan/        | pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block

2:13PM INF Sling Replication Completed in 46m 20s | GOOGLE_STORAGE -> POSTGRES | 4 Successes | 8 Failures


fatal:
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
Replication failure (8 streams failed)
```
