### ISSUE TITLE
Oracle NUMBER(p,s) decimal scale dropped to zero in Sling v1.4.5–v1.4.10

### ISSUE THREAD

**Issue by SIVERTKRISTIANSEN** [slingdata-io/sling-cli#584]
**Description of the issue:**

After upgrading from v1.4.4 to v1.4.10, we’re seeing inconsistent handling of Oracle NUMBER(p,s) columns on incremental loads: Fractional values (e.g. 0.09941) end up as 0.00000. In v1.4.4 all values were preserved accurately.
 
Versions

•	Sling CLI: v1.4.10 (linux amd64)

•	Oracle: 19c via Go driver

•	Target: Snowflake
 
 
- Replication Configuration: 

```
CREATE TABLE test_precision (

  id            NUMBER(10,0),

  value_decimal NUMBER(12,6)

);

INSERT INTO test_precision (id, value_decimal) VALUES (1, 0.01233);

COMMIT;
```

```

source: oracle

target: snowflake

defaults:

  mode: truncate

  object: ods.{stream_table}  

  # disabled: true

  source_options:

    max_decimals: 38

  target_options:

    max_decimals: 38

    adjust_column_type: false
 
streams:

  test_precision:

    object: demo_test_precision

    primary_key: [id]

    update_key: id

    mode: incremental
 
  ...

```
```
SELECT value_decimal
FROM ods.demo_test_precision;

-- Actual:   0.0000000000
-- Expected: 0.0123300000
```
**Expected Behavior**

Sling should read Oracle’s data_scale/data_precision metadata and emit a Snowflake column of NUMBER(12,6), preserving the full fractional value (e.g. 0.01233)

We suspect the error was introduced here: https://github.com/slingdata-io/sling-cli/commit/aa62c316596e1c7d30b5af9c9829fc8bef1bfa46
