### ISSUE TITLE
The file split option does not work on AWS S3.

### ISSUE THREAD

**Issue by nw-bongheelee** [slingdata-io/sling-cli#60]
hello. 
I'm testing AWS S3 as a data load target.

I have written a yaml file like below to store the files in 4000 bytes increments.

```
defaults:
  mode: full-refresh
  
  target_options:
    file_max_bytes: 4000
    format: parquet

streams:
  test.dummy_data:
    object: s3://test-bucket/temporary/sling/

```

When I checked S3 after the synchronization was completed, the file splitting was not done and the data was loaded into only 1 file.

Is it possible that I wrote the yaml incorrectly?

thanks.
