### ISSUE TITLE
Add support for S3 STS based Authentication (Session Tokens)

### ISSUE THREAD

**Issue by ShahBinoy** [slingdata-io/sling-cli#79]
Hi,

The current configuration documentation, https://docs.slingdata.io/connections/file-connections/s3 does not allow for STS session tokens to be passed to the tool via configuration. It does not mention of a `folder` prefix for data location for destination.

Please enhance S3 support to accept STS Session tokens along with ACCESS_ID and SECRET_KEY for AWS connectivity.

Also please add support to prefix the destination file path

Additionally, lot of systems just accept/read the default AWS environment variables. Please have these environment variables be picked so as skip the need to configure if ENV variables are present
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

Or reading Credential Chain via Profile too

```
export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
export AWS_DEFAULT_REGION=us-west-2
export AWS_SESSION_TOKEN=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY/wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY/wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
export AWS_PROFILE=my-custom-profile
```

**Comment by flarco** [comment]
Hi, thanks for the suggestions.

There is actually already some of the functionality you described, it was just not documented. I just updated the docs.
It should already pick up the env vars you mentioned, except for `AWS_PROFILE`, and `AWS_DEFAULT_REGION` (sling picks up `AWS_REGION` instead). It should also pick up `AWS_SESSION_TOKEN`. Can you give it a try?

The reading from the profile is missing, though, so I'll look into adding that.

For example, this should work below, we don't have to specify `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in our `env.yaml`, just the `type` and the `bucket`.

```
export s3='{type: s3, bucket: my-bucket}'
export AWS_ACCESS_KEY_ID= AKIAIOSFODNN7EXAMPLE
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
export AWS_SESSION_TOKEN=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY/wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY/wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY


sling conns test s3

```

**Comment by flarco** [comment]
Just some links for adding profile functionality:
- https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html

**Comment by flarco** [comment]
Can you explain what you mean by `path_prefix`? I am unfamiliar.

**Comment by ShahBinoy** [comment]
> Can you explain what you mean by `path_prefix`? I am unfamiliar. Is this some parameter accepted by AWS S3?

So by path_prefix, it should be possible for the files to be written to a desired path convention that can be controlled from CLI or configs

**path_prefix**=`/elt/datadumps/format=parquet/`
OR
**path_prefix**=`/elt/data_dumps/2022/11/23/`

So if my s3 bucket is `my-fancy-s3-bucket/` I want the files to be dumped at `s3://my-fancy-s3-bucket/elt/datadumps/format=parquet/<sling-generated-file-name>.parquet` | `.csv.gz` | etc.

Hope that clarifies it

**Comment by flarco** [comment]
Thanks, this functionality already exists. I think it's best if you apply this in your [replication config](https://docs.slingdata.io/sling-cli/run/configuration#replication-config). There are many ways to format your target object path with patterns, see [here](https://docs.slingdata.io/sling-cli/run/configuration#object-patterns).

Here is an example replication config:

```yaml
source: MY_SOURCE_DB
target: MY_S3_STORAGE

defaults:
  object: elt/datadumps/format=parquet/{stream_schema}/{stream_table}/{YYYY}_{MM}_{DD}.parquet
  target_options:
    format: parquet

streams:
  my_schema.source_table: # will use defaults

  my_schema.source_table2:
    # override default object pattern
    object: elt/data_dumps/{YYYY}_{MM}_{DD}/my_schema.source_table2.parquet

  # all tables in schema, except "forbidden_table"
  other_schema.*:
    object: elt/data_dumps/{YYYY}_{MM}_{DD}/{stream_schema}/{stream_table}
    target_options:
      file_max_rows: 400000 # will split files into folder
  other_schema.forbidden_table:
    disabled: true
```
